SAPTeam.Kryptor.Client.SessionHost Class Reference
Represents abstraction for session hosts.
Public Member Functions
void Start (ClientContext context)
Starts the host session in the current thread.
Parameters
context The caller context.
virtual void End (bool cancelled)
Ends the host session.
Parameters
cancelled Whether the host session ending triggered by cancel request.
virtual void NewSession (ISession session, bool autoRemove=false, bool autoStart=true)
Starts a new session in this session host.
Parameters
session A session with status SessionStatus.NotStarted.
autoRemove Determines whether to automatically remove session after end.
autoStart Determines whether to automatically call the session manager to start this session.
virtual void MonitorTask (Task task)
Adds given task to the task pool and be monitored by the session host.
Parameters
task The task to be monitored.
Task< TResponse > OnSessionRequest< TResponse > (ISession session, SessionRequest< TResponse > request, CancellationToken cancellationToken)
Handles requests from the sessions.
This method should send requests to user and if it's not possible, it could return the SessionRequest<TResponse>.DefaultValue or throws an exception. The thrown exception would be catched on the sender session and the session will fail.
Public Member Functions inherited from SAPTeam.Kryptor.Client.ISessionHost
Protected Member Functions
SessionHost ()
Initializes all SessionHost instances.
Properties
SessionContainer Container [get]
Gets the session container.
bool Verbose [get, protected set]
Gets the verbosity of the session host.
CancellationTokenSource MasterToken [get]
Gets the special cancellation token to use in non-standard codes. (Blocking codes outside of sessions)
Properties inherited from SAPTeam.Kryptor.Client.ISessionHost
Detailed Description
Represents abstraction for session hosts.
Definition at line 6 of file src/Kryptor.Client/SessionHost.cs.
Constructor & Destructor Documentation
SessionHost()
SAPTeam.Kryptor.Client.SessionHost.SessionHost () [protected]
Initializes all SessionHost instances.
Definition at line 26 of file src/Kryptor.Client/SessionHost.cs.
References SAPTeam.Kryptor.Client.SessionHost.Container, and SAPTeam.Kryptor.Client.SessionHost.MasterToken.
Member Function Documentation
End()
virtual void SAPTeam.Kryptor.Client.SessionHost.End (bool cancelled) [virtual]
Ends the host session.
Parameters
cancelled Whether the host session ending triggered by cancel request.
Implements SAPTeam.Kryptor.Client.ISessionHost.
Definition at line 36 of file src/Kryptor.Client/SessionHost.cs.
References SAPTeam.Kryptor.Client.SessionContainer.Cancel(), SAPTeam.Kryptor.Client.SessionHost.Container, SAPTeam.Kryptor.Client.SessionHost.MasterToken, SAPTeam.Kryptor.Client.SessionContainer.StartQueuedSessions(), and SAPTeam.Kryptor.Client.SessionContainer.WaitForRunningTasks().
MonitorTask()
virtual void SAPTeam.Kryptor.Client.SessionHost.MonitorTask (Task task) [virtual]
Adds given task to the task pool and be monitored by the session host.
Parameters
task The task to be monitored.
Implements SAPTeam.Kryptor.Client.ISessionHost.
Referenced by SAPTeam.Kryptor.Cli.CliSessionHost.ShowProgressMonitored(), and SAPTeam.Kryptor.Cli.CliSessionHost.ShowProgressMonitored().
NewSession()
virtual void SAPTeam.Kryptor.Client.SessionHost.NewSession (ISession session, bool autoRemove = false, bool autoStart = true) [virtual]
Starts a new session in this session host.
Parameters
session A session with status SessionStatus.NotStarted.
autoRemove Determines whether to automatically remove session after end.
autoStart Determines whether to automatically call the session manager to start this session.
Implements SAPTeam.Kryptor.Client.ISessionHost.
Referenced by SAPTeam.Kryptor.Cli.CliSessionHost.LoadKeyStore(), SAPTeam.Kryptor.Cli.DecryptionSessionHost.Start(), SAPTeam.Kryptor.Cli.EncryptionSessionHost.Start(), SAPTeam.Kryptor.Cli.KeyStoreAnalyze.SessionHost.Start(), SAPTeam.Kryptor.Cli.KeyStoreGenerateSessionHost.Start(), SAPTeam.Kryptor.Cli.Wordlist.ImportSessionHost.Start(), and SAPTeam.Kryptor.Cli.Wordlist.QuerySessionHost.Start().
OnSessionRequest< TResponse >()
Task< TResponse > SAPTeam.Kryptor.Client.SessionHost.OnSessionRequest< TResponse > (ISession session, SessionRequest< TResponse > request, CancellationToken cancellationToken) [abstract]
Handles requests from the sessions.
This method should send requests to user and if it's not possible, it could return the SessionRequest<TResponse>.DefaultValue or throws an exception. The thrown exception would be catched on the sender session and the session will fail.
Implements SAPTeam.Kryptor.Client.ISessionHost.
Start()
void SAPTeam.Kryptor.Client.SessionHost.Start (ClientContext context) [abstract]
Starts the host session in the current thread.
Parameters
context The caller context.
Implements SAPTeam.Kryptor.Client.ISessionHost.
Property Documentation
Container
SessionContainer SAPTeam.Kryptor.Client.SessionHost.Container [get], [protected]
Gets the session container.
Definition at line 13 of file src/Kryptor.Client/SessionHost.cs.
Referenced by SAPTeam.Kryptor.Client.SessionHost.End(), SAPTeam.Kryptor.Client.SessionHost.SessionHost(), SAPTeam.Kryptor.Cli.DecryptionSessionHost.Start(), SAPTeam.Kryptor.Cli.EncryptionSessionHost.Start(), SAPTeam.Kryptor.Cli.KeyStoreAnalyze.SessionHost.Start(), and SAPTeam.Kryptor.Cli.Wordlist.QuerySessionHost.Start().
MasterToken
CancellationTokenSource SAPTeam.Kryptor.Client.SessionHost.MasterToken [get], [protected]
Gets the special cancellation token to use in non-standard codes. (Blocking codes outside of sessions)
Definition at line 21 of file src/Kryptor.Client/SessionHost.cs.
Referenced by SAPTeam.Kryptor.Client.SessionHost.End(), and SAPTeam.Kryptor.Client.SessionHost.SessionHost().
Verbose
bool SAPTeam.Kryptor.Client.SessionHost.Verbose [get], [protected set]
Gets the verbosity of the session host.
Implements SAPTeam.Kryptor.Client.ISessionHost.
Definition at line 16 of file src/Kryptor.Client/SessionHost.cs.
Referenced by SAPTeam.Kryptor.Cli.CliSessionHost.CliSessionHost(), SAPTeam.Kryptor.Cli.CliSessionHost.CreateKeyStoreLoadSession(), SAPTeam.Kryptor.Cli.CliSessionHost.DebugLog(), SAPTeam.Kryptor.Cli.EncryptionSession.RunAsync(), SAPTeam.Kryptor.Cli.CliSessionHost.Start(), and SAPTeam.Kryptor.Cli.HeaderReaderSessionHost.Start().
The documentation for this class was generated from the following file:
src/Kryptor.Client/SessionHost.cs