SAPTeam.Kryptor.Client.SessionGroup Class Reference
Provides High-Performance session monitoring solution.
Public Member Functions
void ThrowIfLocked ()
Throws a new InvalidOperationException when the session group is locked.
void Add (SessionHolder item)
void Clear ()
bool Contains (SessionHolder item)
void CopyTo (SessionHolder[] array, int arrayIndex)
bool Remove (SessionHolder item)
IEnumerator< SessionHolder > GetEnumerator ()
Protected Member Functions
void AddHooks (SessionHolder sessionHolder)
Wires up hooks to listen for session events.
Properties
int Waiting [get]
Gets the number of the sessions with SessionStatus.NotStarted status.
int Running [get]
Gets the number of the sessions with SessionStatus.Running status.
int Ended [get]
Gets the number of the sessions with SessionStatus.Ended status.
int Completed [get]
Gets the number of the ended sessions with SessionEndReason.Completed end reason.
int Cancelled [get]
Gets the number of the ended sessions with SessionEndReason.Cancelled end reason.
int Failed [get]
Gets the number of the ended sessions with SessionEndReason.Failed end reason.
int Skipped [get]
Gets the number of the ended sessions with SessionEndReason.Skipped end reason.
int Unknown [get]
Gets the number of the ended sessions with SessionEndReason.None end reason.
SessionStatus Status [get]
Gets the brief report of all session's statuses.
SessionEndReason EndReason [get]
Gets a brief report of all session's end reasons.
string[] Messages [get]
Gets all session messages.
Stopwatch Timer = new Stopwatch() [get]
Gets the timer of the session group.
double Progress [get]
Gets the average progress percentage of all sessions.
bool IsLocked [get]
Gets a bool indicates the lock status of this session group.
int Count [get]
bool IsReadOnly [get]
Detailed Description
Provides High-Performance session monitoring solution.
Definition at line 10 of file SessionGroupStorage.cs.
Member Function Documentation
Add()
void SAPTeam.Kryptor.Client.SessionGroup.Add (SessionHolder item)
Definition at line 43 of file SessionGroupStorage.cs.
References SAPTeam.Kryptor.Client.SessionGroup.AddHooks(), SAPTeam.Kryptor.Client.ISession.IsReady(), SAPTeam.Kryptor.Client.SessionHolder.Session, SAPTeam.Kryptor.Client.ISession.Status, and SAPTeam.Kryptor.Client.SessionGroup.ThrowIfLocked().
Referenced by SAPTeam.Kryptor.Client.SessionContainer.NewSession().
AddHooks()
void SAPTeam.Kryptor.Client.SessionGroup.AddHooks (SessionHolder sessionHolder) [protected]
Wires up hooks to listen for session events.
Parameters
sessionHolder
Definition at line 132 of file SessionGroup.cs.
References SAPTeam.Kryptor.Client.SessionHolder.Session, and SAPTeam.Kryptor.Client.SessionGroup.Waiting.
Referenced by SAPTeam.Kryptor.Client.SessionGroup.Add().
Clear()
void SAPTeam.Kryptor.Client.SessionGroup.Clear ()
Definition at line 73 of file SessionGroupStorage.cs.
References SAPTeam.Kryptor.Client.SessionGroup.ThrowIfLocked().
Contains()
bool SAPTeam.Kryptor.Client.SessionGroup.Contains (SessionHolder item)
CopyTo()
void SAPTeam.Kryptor.Client.SessionGroup.CopyTo (SessionHolder[] array, int arrayIndex)
GetEnumerator()
IEnumerator< SessionHolder > SAPTeam.Kryptor.Client.SessionGroup.GetEnumerator ()
Remove()
bool SAPTeam.Kryptor.Client.SessionGroup.Remove (SessionHolder item)
Definition at line 86 of file SessionGroupStorage.cs.
References SAPTeam.Kryptor.Client.SessionGroup.ThrowIfLocked().
ThrowIfLocked()
void SAPTeam.Kryptor.Client.SessionGroup.ThrowIfLocked ()
Throws a new InvalidOperationException when the session group is locked.
Exceptions
InvalidOperationException
Definition at line 28 of file SessionGroupStorage.cs.
References SAPTeam.Kryptor.Client.SessionGroup.IsLocked.
Referenced by SAPTeam.Kryptor.Client.SessionGroup.Add(), SAPTeam.Kryptor.Client.SessionGroup.Clear(), SAPTeam.Kryptor.Client.SessionContainer.NewSession(), and SAPTeam.Kryptor.Client.SessionGroup.Remove().
Property Documentation
Cancelled
int SAPTeam.Kryptor.Client.SessionGroup.Cancelled [get]
Gets the number of the ended sessions with SessionEndReason.Cancelled end reason.
Definition at line 57 of file SessionGroup.cs.
Completed
int SAPTeam.Kryptor.Client.SessionGroup.Completed [get]
Gets the number of the ended sessions with SessionEndReason.Completed end reason.
Definition at line 52 of file SessionGroup.cs.
Count
int SAPTeam.Kryptor.Client.SessionGroup.Count [get]
Definition at line 37 of file SessionGroupStorage.cs.
Referenced by SAPTeam.Kryptor.Cli.DataProcessingSessionHost.GetSmartProgress().
Ended
int SAPTeam.Kryptor.Client.SessionGroup.Ended [get]
Gets the number of the sessions with SessionStatus.Ended status.
Definition at line 47 of file SessionGroup.cs.
EndReason
SessionEndReason SAPTeam.Kryptor.Client.SessionGroup.EndReason [get]
Gets a brief report of all session's end reasons.
When all sessions ended successfully, the end reason would be SessionEndReason.Completed.
When there is any cancelled session, the end reason would be SessionEndReason.Cancelled.
When there is any failed session, the end reason would be SessionEndReason.Failed.
When there is any skipped session, the end reason would be SessionEndReason.Skipped.
When there is any wierd session or when the session group is not started or still running with no ended session, the end reason would be SessionEndReason.None.
Except for the first case, in other cases the first occurrence is considered. even when there are still running or not started sessions.
Definition at line 105 of file SessionGroup.cs.
Failed
int SAPTeam.Kryptor.Client.SessionGroup.Failed [get]
Gets the number of the ended sessions with SessionEndReason.Failed end reason.
Definition at line 62 of file SessionGroup.cs.
IsLocked
bool SAPTeam.Kryptor.Client.SessionGroup.IsLocked [get]
Gets a bool indicates the lock status of this session group.
Whenever the first session has been started, the session group will be locked.
Definition at line 22 of file SessionGroupStorage.cs.
Referenced by SAPTeam.Kryptor.Client.SessionContainer.SetSessionGroup(), and SAPTeam.Kryptor.Client.SessionGroup.ThrowIfLocked().
IsReadOnly
bool SAPTeam.Kryptor.Client.SessionGroup.IsReadOnly [get]
Definition at line 40 of file SessionGroupStorage.cs.
Messages
string [] SAPTeam.Kryptor.Client.SessionGroup.Messages [get]
Gets all session messages.
This list only updated whenever a session is ended.
Definition at line 113 of file SessionGroup.cs.
Progress
double SAPTeam.Kryptor.Client.SessionGroup.Progress [get]
Gets the average progress percentage of all sessions.
Definition at line 126 of file SessionGroup.cs.
Running
int SAPTeam.Kryptor.Client.SessionGroup.Running [get]
Gets the number of the sessions with SessionStatus.Running status.
Definition at line 42 of file SessionGroup.cs.
Skipped
int SAPTeam.Kryptor.Client.SessionGroup.Skipped [get]
Gets the number of the ended sessions with SessionEndReason.Skipped end reason.
Definition at line 67 of file SessionGroup.cs.
Status
SessionStatus SAPTeam.Kryptor.Client.SessionGroup.Status [get]
Gets the brief report of all session's statuses.
When there are no sessions started yet, the status would be SessionStatus.NotStarted.
Whenever the first session is started, the status would be SessionStatus.Running.
When all of the sessions is ended, the status would be SessionStatus.Ended.
Definition at line 84 of file SessionGroup.cs.
Timer
Stopwatch SAPTeam.Kryptor.Client.SessionGroup.Timer = new Stopwatch() [get]
Gets the timer of the session group.
This timer started when the first session is started and stopped when the last session is ended.
Definition at line 121 of file SessionGroup.cs.
Unknown
int SAPTeam.Kryptor.Client.SessionGroup.Unknown [get]
Gets the number of the ended sessions with SessionEndReason.None end reason.
Definition at line 72 of file SessionGroup.cs.
Waiting
int SAPTeam.Kryptor.Client.SessionGroup.Waiting [get]
Gets the number of the sessions with SessionStatus.NotStarted status.
Definition at line 37 of file SessionGroup.cs.
Referenced by SAPTeam.Kryptor.Client.SessionGroup.AddHooks().
The documentation for this class was generated from the following files:
SessionGroup.cs
SessionGroupStorage.cs