SAPTeam.Kryptor.Client.SessionContainer Class Reference
Represents container to store sessions.
Public Member Functions
int Add (SessionHolder sessionHolder)
Adds new session to the container.
void AddMonitoringTask (Task task)
Adds just a task to Tasks.
void Remove (int id)
Removes an entry from the container.
SessionContainer (ISessionHost sessionHost, int maxRunningSessions)
Initializes a new instance of the SessionContainer class.
async Task WaitAll (CancellationToken cancellationToken)
Waits until all sessions have been ended.
void WaitForRunningTasks ()
Waits for all running tasks at the moment to end.
void Cancel ()
Sends cancellation request to all cancellation tokens in this container.
SessionGroup SetSessionGroup (SessionGroup sessionGroup)
Sets the provided sessionGroup as the SessionManager's cache system.
void NewSession (ISession session, bool autoRemove, bool autoStart)
Starts a new session in this container.
void StartQueuedSessions ()
Starts registered sessions in a managed way.
Static Public Member Functions
static SessionHolder WrapSession (ISession session, bool autoRemove)
Wraps the given session into a SessionHolder.
Properties
ISession[] Sessions [get]
Gets an array of all sessions.
Task[] Tasks [get]
Gets an array of all tasks.
CancellationTokenSource[] TokenSources [get]
Gets an array of all cancellation tokens.
ICollection< SessionHolder > Holders [get]
Gets all session holders.
int MaxRunningSessions [get, set]
Gets or sets the maximum allowed running sessions.
Detailed Description
Represents container to store sessions.
Definition at line 5 of file SessionManager.cs.
Constructor & Destructor Documentation
SessionContainer()
SAPTeam.Kryptor.Client.SessionContainer.SessionContainer (ISessionHost sessionHost, int maxRunningSessions)
Initializes a new instance of the SessionContainer class.
Parameters
sessionHost The parent session host.
maxRunningSessions The maximum allowed running sessions.
Definition at line 26 of file SessionManager.cs.
References SAPTeam.Kryptor.Client.SessionContainer.MaxRunningSessions.
Member Function Documentation
Add()
int SAPTeam.Kryptor.Client.SessionContainer.Add (SessionHolder sessionHolder)
Adds new session to the container.
Returns
The unique identifier of this entry.
Definition at line 63 of file SessionContainer.cs.
Referenced by SAPTeam.Kryptor.Client.SessionContainer.NewSession().
AddMonitoringTask()
void SAPTeam.Kryptor.Client.SessionContainer.AddMonitoringTask (Task task)
Adds just a task to Tasks.
Parameters
task The task to be added.
Definition at line 81 of file SessionContainer.cs.
Cancel()
void SAPTeam.Kryptor.Client.SessionContainer.Cancel ()
Sends cancellation request to all cancellation tokens in this container.
Definition at line 77 of file SessionManager.cs.
References SAPTeam.Kryptor.Client.SessionContainer.TokenSources.
Referenced by SAPTeam.Kryptor.Client.SessionHost.End(), and SAPTeam.Kryptor.Client.SessionContainer.WaitAll().
NewSession()
void SAPTeam.Kryptor.Client.SessionContainer.NewSession (ISession session, bool autoRemove, bool autoStart)
Starts a new session in this container.
Parameters
session A session with status SessionStatus.NotStarted.
autoRemove Determines whether to automatically remove session after end.
autoStart Determines whether to automatically call the session manager's task schedular to start the session. This value is ignored when a valid session group was set.
Definition at line 145 of file SessionManager.cs.
References SAPTeam.Kryptor.Client.SessionContainer.Add(), SAPTeam.Kryptor.Client.SessionGroup.Add(), SAPTeam.Kryptor.Client.SessionContainer.StartQueuedSessions(), SAPTeam.Kryptor.Client.SessionGroup.ThrowIfLocked(), and SAPTeam.Kryptor.Client.SessionContainer.WrapSession().
Remove()
void SAPTeam.Kryptor.Client.SessionContainer.Remove (int id)
Removes an entry from the container.
Parameters
id The unique identifier returned by Add call.
Definition at line 96 of file SessionContainer.cs.
SetSessionGroup()
SessionGroup SAPTeam.Kryptor.Client.SessionContainer.SetSessionGroup (SessionGroup sessionGroup)
Sets the provided sessionGroup as the SessionManager's cache system.
The provided session group must be unused and unlocked. If a session group is already set, it must be fully finnished, otherwise it will throw a InvalidOperationException. A new instance of the SessionGroup class is always unlocked. It's highly recommended to use a new session group.
Parameters
sessionGroup A new session group with unlocked status.
Returns
sessionGroup
Exceptions
InvalidOperationException
ArgumentNullException
ArgumentException
Definition at line 101 of file SessionManager.cs.
References SAPTeam.Kryptor.Client.SessionGroup.IsLocked.
Referenced by SAPTeam.Kryptor.Cli.DecryptionSessionHost.Start(), and SAPTeam.Kryptor.Cli.EncryptionSessionHost.Start().
StartQueuedSessions()
void SAPTeam.Kryptor.Client.SessionContainer.StartQueuedSessions ()
Starts registered sessions in a managed way.
This is the core of the Session based Application Model logic. This task scheduler logic works with checking the number of running sessions (sessions with status SessionStatus.Running) and checking the waiting sessions (sessions with status SessionStatus.NotStarted and be ready). The ready to run sessions determined by calling the ISession.IsReady(CancellationToken) method, if the return value is true the session will be added to the waiting list, otherwise it will be ignored and rechecked at the next run of the task scheduler. There is some important notes about this process.
The task scheduler only runs after each NewSession(ISession, bool, bool)calls and session ends. so if there is two sessions and the second session does not get ready until first session end, the task scheduler won't try to run that session and it will stuck at waiting status.
The ISession.IsReady(CancellationToken) should not throw ANY exceptions at all. it may break the scheduler. Although there is some layers to handle exceptions, but the ISession.IsReady(CancellationToken) is only allwed to response with true or false.
Definition at line 208 of file SessionManager.cs.
Referenced by SAPTeam.Kryptor.Client.SessionHost.End(), SAPTeam.Kryptor.Client.SessionContainer.NewSession(), SAPTeam.Kryptor.Cli.DecryptionSessionHost.Start(), and SAPTeam.Kryptor.Cli.EncryptionSessionHost.Start().
WaitAll()
async Task SAPTeam.Kryptor.Client.SessionContainer.WaitAll (CancellationToken cancellationToken)
Waits until all sessions have been ended.
This method also waits for sessions that are not started yet. If the cancellationToken was cancelled, this method will cancel all existing tokens in this container and waits for all of them to end. This method intended to be used by sub-session models. in standard session host based model, the monitoring, cancelling and ending is managed by various parts. But in sub-session models, you could achieve all of these features in this method. Using this method in session host is not recommended at all because this method is not intended for that porpose.
Parameters
cancellationToken The token to monitor for cancellation requests.
Definition at line 45 of file SessionManager.cs.
References SAPTeam.Kryptor.Client.SessionContainer.Cancel(), and SAPTeam.Kryptor.Client.SessionContainer.Sessions.
WaitForRunningTasks()
void SAPTeam.Kryptor.Client.SessionContainer.WaitForRunningTasks ()
Waits for all running tasks at the moment to end.
This method just waits for running tasks and does not care about waiting sessions (as they don't have a registered task). A Task must be registered by AddMonitoringTask(Task) that waits for not started sessions before calling this method. This method only intended to be used in ISessionHost.End(bool). so using it in sub-session models is not recommended as it could be lead to unexpected session exit and losing control of sub-sessions. it's highly recommended to use WaitAll(CancellationToken) method in that situation.
Referenced by SAPTeam.Kryptor.Client.SessionHost.End().
WrapSession()
static SessionHolder SAPTeam.Kryptor.Client.SessionContainer.WrapSession (ISession session, bool autoRemove) [static]
Wraps the given session into a SessionHolder.
Parameters
session A session with status SessionStatus.NotStarted.
autoRemove Determines whether to automatically remove session after end.
Returns
Definition at line 174 of file SessionManager.cs.
References SAPTeam.Kryptor.Client.ISession.Status.
Referenced by SAPTeam.Kryptor.Client.SessionContainer.NewSession().
Property Documentation
Holders
ICollection<SessionHolder> SAPTeam.Kryptor.Client.SessionContainer.Holders [get]
Gets all session holders.
Definition at line 49 of file SessionContainer.cs.
MaxRunningSessions
int SAPTeam.Kryptor.Client.SessionContainer.MaxRunningSessions [get], [set]
Gets or sets the maximum allowed running sessions.
Definition at line 15 of file SessionManager.cs.
Referenced by SAPTeam.Kryptor.Client.SessionContainer.SessionContainer().
Sessions
ISession [] SAPTeam.Kryptor.Client.SessionContainer.Sessions [get]
Gets an array of all sessions.
Definition at line 18 of file SessionContainer.cs.
Referenced by SAPTeam.Kryptor.Cli.KeyStoreAnalyze.SessionHost.Start(), SAPTeam.Kryptor.Cli.Wordlist.QuerySessionHost.Start(), and SAPTeam.Kryptor.Client.SessionContainer.WaitAll().
Tasks
Task [] SAPTeam.Kryptor.Client.SessionContainer.Tasks [get]
Gets an array of all tasks.
Definition at line 31 of file SessionContainer.cs.
TokenSources
CancellationTokenSource [] SAPTeam.Kryptor.Client.SessionContainer.TokenSources [get]
Gets an array of all cancellation tokens.
Definition at line 36 of file SessionContainer.cs.
Referenced by SAPTeam.Kryptor.Client.SessionContainer.Cancel().
The documentation for this class was generated from the following files:
SessionContainer.cs
SessionManager.cs