SAPTeam.Kryptor.Cli.KeyStoreGenerateSessionHost Class Reference
Public Member Functions
KeyStoreGenerateSessionHost (GlobalOptions globalOptions, KeyStoreGenerator generator, int size, TransformerToken token, int magin, string output)
override void Start (ClientContext context)
Starts the host session in the current thread.
Public Member Functions inherited from SAPTeam.Kryptor.Cli.CliSessionHost
CliSessionHost (GlobalOptions globalOptions)
override void Start (ClientContext context)
Starts the host session in the current thread.
override async Task< TResponse > OnSessionRequest< TResponse > (ISession session, SessionRequest< TResponse > request, CancellationToken cancellationToken)
Handles requests from the sessions.
Public Member Functions inherited from SAPTeam.Kryptor.Client.SessionHost
void Start (ClientContext context)
Starts the host session in the current thread.
Parameters
context The caller context.
virtual void End (bool cancelled)
Ends the host session.
Parameters
cancelled Whether the host session ending triggered by cancel request.
virtual void NewSession (ISession session, bool autoRemove=false, bool autoStart=true)
Starts a new session in this session host.
Parameters
session A session with status SessionStatus.NotStarted.
autoRemove Determines whether to automatically remove session after end.
autoStart Determines whether to automatically call the session manager to start this session.
virtual void MonitorTask (Task task)
Adds given task to the task pool and be monitored by the session host.
Parameters
task The task to be monitored.
Task< TResponse > OnSessionRequest< TResponse > (ISession session, SessionRequest< TResponse > request, CancellationToken cancellationToken)
Handles requests from the sessions.
This method should send requests to user and if it's not possible, it could return the SessionRequest<TResponse>.DefaultValue or throws an exception. The thrown exception would be catched on the sender session and the session will fail.
Public Member Functions inherited from SAPTeam.Kryptor.Client.ISessionHost
Static Public Member Functions
static void CollectEntropy ()
Additional Inherited Members
Protected Member Functions inherited from SAPTeam.Kryptor.Cli.CliSessionHost
void Log (string message=null)
void LogError (string message=null)
void DebugLog (string message)
Task ShowProgress (bool showOverall, bool showRemaining)
Task ShowProgressMonitored (bool showOverall, bool showRemaining=true)
Task ShowProgress (SessionGroup sessionGroup)
Task ShowProgressMonitored (SessionGroup sessionGroup)
KeyStore LoadKeyStore (string keyStore)
KeyStoreLoadSession CreateKeyStoreLoadSession (string keyStore)
Protected Member Functions inherited from SAPTeam.Kryptor.Client.SessionHost
SessionHost ()
Initializes all SessionHost instances.
Properties inherited from SAPTeam.Kryptor.Cli.CliSessionHost
bool Quiet [get]
bool NoColor [get]
bool NoInteractions [get]
bool IsOutputRedirected [get]
PauseRequest Request = new PauseRequest(null, false) [get]
bool HasRequest [get]
ConsoleKeyInfo KeyQueue [get, set]
Properties inherited from SAPTeam.Kryptor.Client.SessionHost
SessionContainer Container [get]
Gets the session container.
bool Verbose [get, protected set]
Gets the verbosity of the session host.
CancellationTokenSource MasterToken [get]
Gets the special cancellation token to use in non-standard codes. (Blocking codes outside of sessions)
Properties inherited from SAPTeam.Kryptor.Client.ISessionHost
Detailed Description
Definition at line 8 of file KeyStoreGenerateSessionHost.cs.
Constructor & Destructor Documentation
KeyStoreGenerateSessionHost()
SAPTeam.Kryptor.Cli.KeyStoreGenerateSessionHost.KeyStoreGenerateSessionHost (GlobalOptions globalOptions, KeyStoreGenerator generator, int size, TransformerToken token, int magin, string output)
Definition at line 16 of file KeyStoreGenerateSessionHost.cs.
References SAPTeam.Kryptor.KeyStore.GetRandomOddNumber().
Member Function Documentation
CollectEntropy()
static void SAPTeam.Kryptor.Cli.KeyStoreGenerateSessionHost.CollectEntropy () [static]
Definition at line 60 of file KeyStoreGenerateSessionHost.cs.
References SAPTeam.Kryptor.Generators.EntroX.AddEntropy(), and SAPTeam.Kryptor.Generators.CryptoRandom.Next().
Referenced by SAPTeam.Kryptor.Cli.KeyStoreGenerateSessionHost.Start().
Start()
override void SAPTeam.Kryptor.Cli.KeyStoreGenerateSessionHost.Start (ClientContext context)
Starts the host session in the current thread.
Parameters
context The caller context.
Implements SAPTeam.Kryptor.Client.ISessionHost.
Definition at line 25 of file KeyStoreGenerateSessionHost.cs.
References SAPTeam.Kryptor.Cli.KeyStoreGenerateSessionHost.CollectEntropy(), SAPTeam.Kryptor.Client.Session.ContinueWith(), SAPTeam.Kryptor.TransformerToken.IsValid(), SAPTeam.Kryptor.Cli.CliSessionHost.Log(), SAPTeam.Kryptor.Client.SessionHost.NewSession(), SAPTeam.Kryptor.Cli.CliSessionHost.NoInteractions, and SAPTeam.Kryptor.Cli.CliSessionHost.ShowProgressMonitored().
The documentation for this class was generated from the following file:
KeyStoreGenerateSessionHost.cs