SAPTeam.Kryptor.Cli.DataProcessingSessionHost Class Reference
Public Member Functions
DataProcessingSessionHost (GlobalOptions globalOptions, DataProcessingOptions options)
override void Start (ClientContext context)
Starts the host session in the current thread.
Task GetSmartProgress (SessionGroup sessionGroup)
void EnumerateFiles (Action< string, string > action)
Public Member Functions inherited from SAPTeam.Kryptor.Cli.CliSessionHost
CliSessionHost (GlobalOptions globalOptions)
override void Start (ClientContext context)
Starts the host session in the current thread.
override async Task< TResponse > OnSessionRequest< TResponse > (ISession session, SessionRequest< TResponse > request, CancellationToken cancellationToken)
Handles requests from the sessions.
Public Member Functions inherited from SAPTeam.Kryptor.Client.SessionHost
void Start (ClientContext context)
Starts the host session in the current thread.
Parameters
context The caller context.
virtual void End (bool cancelled)
Ends the host session.
Parameters
cancelled Whether the host session ending triggered by cancel request.
virtual void NewSession (ISession session, bool autoRemove=false, bool autoStart=true)
Starts a new session in this session host.
Parameters
session A session with status SessionStatus.NotStarted.
autoRemove Determines whether to automatically remove session after end.
autoStart Determines whether to automatically call the session manager to start this session.
virtual void MonitorTask (Task task)
Adds given task to the task pool and be monitored by the session host.
Parameters
task The task to be monitored.
Task< TResponse > OnSessionRequest< TResponse > (ISession session, SessionRequest< TResponse > request, CancellationToken cancellationToken)
Handles requests from the sessions.
This method should send requests to user and if it's not possible, it could return the SessionRequest<TResponse>.DefaultValue or throws an exception. The thrown exception would be catched on the sender session and the session will fail.
Public Member Functions inherited from SAPTeam.Kryptor.Client.ISessionHost
Static Public Member Functions
static string GetRelativePath (string relativeTo, string path)
Public Attributes
readonly string KeystoreString
Properties
int BlockSize [get]
CryptoProviderConfiguration Configuration [get]
string OutputPath [get]
KeyStore KeyStore [get]
Properties inherited from SAPTeam.Kryptor.Cli.CliSessionHost
bool Quiet [get]
bool NoColor [get]
bool NoInteractions [get]
bool IsOutputRedirected [get]
PauseRequest Request = new PauseRequest(null, false) [get]
bool HasRequest [get]
ConsoleKeyInfo KeyQueue [get, set]
Properties inherited from SAPTeam.Kryptor.Client.SessionHost
SessionContainer Container [get]
Gets the session container.
bool Verbose [get, protected set]
Gets the verbosity of the session host.
CancellationTokenSource MasterToken [get]
Gets the special cancellation token to use in non-standard codes. (Blocking codes outside of sessions)
Properties inherited from SAPTeam.Kryptor.Client.ISessionHost
Additional Inherited Members
Protected Member Functions inherited from SAPTeam.Kryptor.Cli.CliSessionHost
void Log (string message=null)
void LogError (string message=null)
void DebugLog (string message)
Task ShowProgress (bool showOverall, bool showRemaining)
Task ShowProgressMonitored (bool showOverall, bool showRemaining=true)
Task ShowProgress (SessionGroup sessionGroup)
Task ShowProgressMonitored (SessionGroup sessionGroup)
KeyStore LoadKeyStore (string keyStore)
KeyStoreLoadSession CreateKeyStoreLoadSession (string keyStore)
Protected Member Functions inherited from SAPTeam.Kryptor.Client.SessionHost
SessionHost ()
Initializes all SessionHost instances.
Detailed Description
Definition at line 7 of file DataProcessingSessionHost.cs.
Constructor & Destructor Documentation
DataProcessingSessionHost()
SAPTeam.Kryptor.Cli.DataProcessingSessionHost.DataProcessingSessionHost (GlobalOptions globalOptions, DataProcessingOptions options)
Definition at line 21 of file DataProcessingSessionHost.cs.
References SAPTeam.Kryptor.Cli.DataProcessingOptions.BlockSize, SAPTeam.Kryptor.Cli.DataProcessingSessionHost.BlockSize, SAPTeam.Kryptor.Cli.DataProcessingSessionHost.Configuration, SAPTeam.Kryptor.Cli.DataProcessingOptions.Continuous, SAPTeam.Kryptor.Cli.DataProcessingOptions.DynamicBlockProcessing, SAPTeam.Kryptor.Cli.DataProcessingOptions.Files, SAPTeam.Kryptor.Cli.DataProcessingOptions.KeyStore, SAPTeam.Kryptor.Cli.DataProcessingSessionHost.KeystoreString, SAPTeam.Kryptor.Cli.DataProcessingOptions.OutputPath, SAPTeam.Kryptor.Cli.DataProcessingSessionHost.OutputPath, SAPTeam.Kryptor.Cli.DataProcessingOptions.Provider, and SAPTeam.Kryptor.Cli.DataProcessingOptions.RemoveHash.
Member Function Documentation
EnumerateFiles()
void SAPTeam.Kryptor.Cli.DataProcessingSessionHost.EnumerateFiles (Action< string, string > action)
Definition at line 62 of file DataProcessingSessionHost.cs.
References SAPTeam.Kryptor.Cli.DataProcessingSessionHost.GetRelativePath(), and SAPTeam.Kryptor.Cli.DataProcessingSessionHost.OutputPath.
Referenced by SAPTeam.Kryptor.Cli.DecryptionSessionHost.Start(), and SAPTeam.Kryptor.Cli.EncryptionSessionHost.Start().
GetRelativePath()
static string SAPTeam.Kryptor.Cli.DataProcessingSessionHost.GetRelativePath (string relativeTo, string path) [static]
Definition at line 80 of file DataProcessingSessionHost.cs.
Referenced by SAPTeam.Kryptor.Cli.DataProcessingSessionHost.EnumerateFiles().
GetSmartProgress()
Task SAPTeam.Kryptor.Cli.DataProcessingSessionHost.GetSmartProgress (SessionGroup sessionGroup)
Definition at line 47 of file DataProcessingSessionHost.cs.
References SAPTeam.Kryptor.Client.SessionGroup.Count, and SAPTeam.Kryptor.Cli.CliSessionHost.ShowProgressMonitored().
Referenced by SAPTeam.Kryptor.Cli.DecryptionSessionHost.Start(), and SAPTeam.Kryptor.Cli.EncryptionSessionHost.Start().
Start()
override void SAPTeam.Kryptor.Cli.DataProcessingSessionHost.Start (ClientContext context)
Starts the host session in the current thread.
Parameters
context The caller context.
Implements SAPTeam.Kryptor.Client.ISessionHost.
Definition at line 40 of file DataProcessingSessionHost.cs.
References SAPTeam.Kryptor.Cli.DataProcessingSessionHost.KeystoreString, and SAPTeam.Kryptor.Cli.CliSessionHost.LoadKeyStore().
Member Data Documentation
KeystoreString
readonly string SAPTeam.Kryptor.Cli.DataProcessingSessionHost.KeystoreString
Definition at line 19 of file DataProcessingSessionHost.cs.
Referenced by SAPTeam.Kryptor.Cli.DataProcessingSessionHost.DataProcessingSessionHost(), SAPTeam.Kryptor.Cli.EncryptionSession.RunAsync(), and SAPTeam.Kryptor.Cli.DataProcessingSessionHost.Start().
Property Documentation
BlockSize
int SAPTeam.Kryptor.Cli.DataProcessingSessionHost.BlockSize [get]
Definition at line 11 of file DataProcessingSessionHost.cs.
Referenced by SAPTeam.Kryptor.Cli.DataProcessingSessionHost.DataProcessingSessionHost(), SAPTeam.Kryptor.Cli.DecryptionSessionHost.Start(), and SAPTeam.Kryptor.Cli.EncryptionSessionHost.Start().
Configuration
CryptoProviderConfiguration SAPTeam.Kryptor.Cli.DataProcessingSessionHost.Configuration [get]
Definition at line 13 of file DataProcessingSessionHost.cs.
Referenced by SAPTeam.Kryptor.Cli.DataProcessingSessionHost.DataProcessingSessionHost(), SAPTeam.Kryptor.Cli.DecryptionSessionHost.Start(), and SAPTeam.Kryptor.Cli.EncryptionSessionHost.Start().
KeyStore
KeyStore SAPTeam.Kryptor.Cli.DataProcessingSessionHost.KeyStore [get]
Definition at line 17 of file DataProcessingSessionHost.cs.
OutputPath
string SAPTeam.Kryptor.Cli.DataProcessingSessionHost.OutputPath [get]
Definition at line 15 of file DataProcessingSessionHost.cs.
Referenced by SAPTeam.Kryptor.Cli.DataProcessingSessionHost.DataProcessingSessionHost(), and SAPTeam.Kryptor.Cli.DataProcessingSessionHost.EnumerateFiles().
The documentation for this class was generated from the following file:
DataProcessingSessionHost.cs