SAPTeam.Kryptor.Generators.CryptoRandom Class Reference
A random number generator based on the RNGCryptoServiceProvider. Adapted from the "Tales from the CryptoRandom" article in MSDN Magazine (September 2007) but with explicit guarantee to be thread safe. Note that this implementation also includes an optional (enabled by default) random buffer which provides a significant speed boost as it greatly reduces the amount of calls into unmanaged land.
Public Member Functions
CryptoRandom ()
Initializes a new instance of the CryptoRandom class with. Using this overload will enable the random buffer pool.
CryptoRandom (int ignoredSeed)
Initializes a new instance of the CryptoRandom class. This method will disregard whatever value is passed as seed and it's only implemented in order to be fully backwards compatible with System.Random. Using this overload will enable the random buffer pool.
CryptoRandom (bool enableRandomPool)
Initializes a new instance of the CryptoRandom class with optional random buffer.
void Generate (byte[] buffer)
Fills the buffer with random values.
Parameters
buffer The output buffer.
override int Next ()
Returns a nonnegative random number.
override int Next (int maxValue)
Returns a nonnegative random number less than the specified maximum.
override int Next (int minValue, int maxValue)
Returns a random number within a specified range.
override double NextDouble ()
Returns a random number between 0.0 and 1.0.
override void NextBytes (byte[] buffer)
Fills the elements of a specified array of bytes with random numbers.
Public Member Functions inherited from SAPTeam.Kryptor.IGenerator
Properties
static CryptoRandom Instance = new CryptoRandom() [get]
Gets an static shared instance of the CryptoRandom class.
bool IsRandomPoolEnabled [get]
Gets a value indicating whether this instance has random pool enabled.
Events
EventHandler< double > ProgressChanged
Events inherited from SAPTeam.Kryptor.Helpers.IProgressReport
EventHandler< double > ProgressChanged
Triggered when the work progress is changed.
Detailed Description
A random number generator based on the RNGCryptoServiceProvider. Adapted from the "Tales from the CryptoRandom" article in MSDN Magazine (September 2007) but with explicit guarantee to be thread safe. Note that this implementation also includes an optional (enabled by default) random buffer which provides a significant speed boost as it greatly reduces the amount of calls into unmanaged land.
Definition at line 13 of file CryptoRandom.cs.
Constructor & Destructor Documentation
CryptoRandom() [1/3]
SAPTeam.Kryptor.Generators.CryptoRandom.CryptoRandom ()
Initializes a new instance of the CryptoRandom class with. Using this overload will enable the random buffer pool.
Definition at line 42 of file CryptoRandom.cs.
CryptoRandom() [2/3]
SAPTeam.Kryptor.Generators.CryptoRandom.CryptoRandom (int ignoredSeed)
Initializes a new instance of the CryptoRandom class. This method will disregard whatever value is passed as seed and it's only implemented in order to be fully backwards compatible with System.Random. Using this overload will enable the random buffer pool.
Parameters
ignoredSeed The ignored seed.
Definition at line 52 of file CryptoRandom.cs.
CryptoRandom() [3/3]
SAPTeam.Kryptor.Generators.CryptoRandom.CryptoRandom (bool enableRandomPool)
Initializes a new instance of the CryptoRandom class with optional random buffer.
Parameters
enableRandomPool set to true to enable the random pool buffer for increased performance.
References SAPTeam.Kryptor.Generators.CryptoRandom.IsRandomPoolEnabled.
Member Function Documentation
Generate()
void SAPTeam.Kryptor.Generators.CryptoRandom.Generate (byte[] buffer)
Fills the buffer with random values.
Parameters
buffer The output buffer.
Implements SAPTeam.Kryptor.IGenerator.
Definition at line 79 of file CryptoRandom.cs.
References SAPTeam.Kryptor.Generators.CryptoRandom.NextBytes(), and SAPTeam.Kryptor.Generators.CryptoRandom.ProgressChanged.
Referenced by SAPTeam.Kryptor.Cli.EncryptionSession.RunAsync().
Next() [1/3]
override int SAPTeam.Kryptor.Generators.CryptoRandom.Next ()
Returns a nonnegative random number.
Returns
A 32-bit signed integer greater than or equal to zero and less than F:System.Int32.MaxValue.
Referenced by SAPTeam.Kryptor.Cli.KeyStoreGenerateSessionHost.CollectEntropy().
Next() [2/3]
override int SAPTeam.Kryptor.Generators.CryptoRandom.Next (int maxValue)
Returns a nonnegative random number less than the specified maximum.
Parameters
maxValue The exclusive upper bound of the random number to be generated. maxValue must be greater than or equal to zero.
Returns
A 32-bit signed integer greater than or equal to zero, and less than maxValue ; that is, the range of return values ordinarily includes zero but not maxValue . However, if maxValue equals zero, maxValue is returned.
Exceptions
T:System.ArgumentOutOfRangeException maxValue is less than zero.
Next() [3/3]
override int SAPTeam.Kryptor.Generators.CryptoRandom.Next (int minValue, int maxValue)
Returns a random number within a specified range.
Parameters
minValue The inclusive lower bound of the random number returned.
maxValue The exclusive upper bound of the random number returned. maxValue must be greater than or equal to minValue .
Returns
A 32-bit signed integer greater than or equal to minValue and less than maxValue ; that is, the range of return values includes minValue but not maxValue . If minValue equals maxValue , minValue is returned.
Exceptions
T:System.ArgumentOutOfRangeException minValue is greater than maxValue .
Definition at line 131 of file CryptoRandom.cs.
NextBytes()
override void SAPTeam.Kryptor.Generators.CryptoRandom.NextBytes (byte[] buffer)
Fills the elements of a specified array of bytes with random numbers.
Parameters
buffer An array of bytes to contain random numbers.
Exceptions
T:System.ArgumentNullException buffer is null.
Definition at line 168 of file CryptoRandom.cs.
References SAPTeam.Kryptor.Generators.CryptoRandom.IsRandomPoolEnabled.
Referenced by SAPTeam.Kryptor.Generators.CryptoRandom.Generate().
NextDouble()
override double SAPTeam.Kryptor.Generators.CryptoRandom.NextDouble ()
Returns a random number between 0.0 and 1.0.
Returns
A double-precision floating point number greater than or equal to 0.0, and less than 1.0.
Property Documentation
Instance
CryptoRandom SAPTeam.Kryptor.Generators.CryptoRandom.Instance = new CryptoRandom() [static], [get]
Gets an static shared instance of the CryptoRandom class.
Definition at line 25 of file CryptoRandom.cs.
Referenced by SAPTeam.Kryptor.Cli.EncryptionSession.RunAsync().
IsRandomPoolEnabled
bool SAPTeam.Kryptor.Generators.CryptoRandom.IsRandomPoolEnabled [get]
Gets a value indicating whether this instance has random pool enabled.
true if this instance has random pool enabled; otherwise, false.
Definition at line 33 of file CryptoRandom.cs.
Referenced by SAPTeam.Kryptor.Generators.CryptoRandom.CryptoRandom(), and SAPTeam.Kryptor.Generators.CryptoRandom.NextBytes().
Event Documentation
ProgressChanged
EventHandler<double> SAPTeam.Kryptor.Generators.CryptoRandom.ProgressChanged
Definition at line 36 of file CryptoRandom.cs.
Referenced by SAPTeam.Kryptor.Generators.CryptoRandom.Generate().
The documentation for this class was generated from the following file:
CryptoRandom.cs