SAPTeam.Kryptor.Cli.Program Class Reference
Static Public Member Functions
static int Main (string[] args)
static RootCommand GetRootCommand ()
Properties
static CliContext Context = CommonTK.Context.Register<CliContext>() [get]
Detailed Description
Definition at line 10 of file Program.cs.
Member Function Documentation
GetRootCommand()
static RootCommand SAPTeam.Kryptor.Cli.Program.GetRootCommand () [static]
Definition at line 21 of file Program.cs.
References SAPTeam.Kryptor.Kes.DefaultBlockSize, and SAPTeam.Kryptor.TransformerToken.IsValid().
Referenced by SAPTeam.Kryptor.Cli.Program.Main().
Main()
static int SAPTeam.Kryptor.Cli.Program.Main (string[] args) [static]
Definition at line 14 of file Program.cs.
References SAPTeam.Kryptor.Cli.Program.GetRootCommand().
Property Documentation
Context
CliContext SAPTeam.Kryptor.Cli.Program.Context = CommonTK.Context.Register<CliContext>() [static], [get]
Definition at line 12 of file Program.cs.
Referenced by SAPTeam.Kryptor.Cli.Wordlist.ImportSessionHost.Start().
The documentation for this class was generated from the following file:
Program.cs