SAPTeam.Kryptor.Cli.CliSessionHost Class Reference
Public Member Functions
CliSessionHost (GlobalOptions globalOptions)
override void Start (ClientContext context)
Starts the host session in the current thread.
override async Task< TResponse > OnSessionRequest< TResponse > (ISession session, SessionRequest< TResponse > request, CancellationToken cancellationToken)
Handles requests from the sessions.
Public Member Functions inherited from SAPTeam.Kryptor.Client.SessionHost
void Start (ClientContext context)
Starts the host session in the current thread.
Parameters
context The caller context.
virtual void End (bool cancelled)
Ends the host session.
Parameters
cancelled Whether the host session ending triggered by cancel request.
virtual void NewSession (ISession session, bool autoRemove=false, bool autoStart=true)
Starts a new session in this session host.
Parameters
session A session with status SessionStatus.NotStarted.
autoRemove Determines whether to automatically remove session after end.
autoStart Determines whether to automatically call the session manager to start this session.
virtual void MonitorTask (Task task)
Adds given task to the task pool and be monitored by the session host.
Parameters
task The task to be monitored.
Task< TResponse > OnSessionRequest< TResponse > (ISession session, SessionRequest< TResponse > request, CancellationToken cancellationToken)
Handles requests from the sessions.
This method should send requests to user and if it's not possible, it could return the SessionRequest<TResponse>.DefaultValue or throws an exception. The thrown exception would be catched on the sender session and the session will fail.
Public Member Functions inherited from SAPTeam.Kryptor.Client.ISessionHost
Protected Member Functions
void Log (string message=null)
void LogError (string message=null)
void DebugLog (string message)
Task ShowProgress (bool showOverall, bool showRemaining)
Task ShowProgressMonitored (bool showOverall, bool showRemaining=true)
Task ShowProgress (SessionGroup sessionGroup)
Task ShowProgressMonitored (SessionGroup sessionGroup)
KeyStore LoadKeyStore (string keyStore)
KeyStoreLoadSession CreateKeyStoreLoadSession (string keyStore)
Protected Member Functions inherited from SAPTeam.Kryptor.Client.SessionHost
SessionHost ()
Initializes all SessionHost instances.
Properties
bool Quiet [get]
bool NoColor [get]
bool NoInteractions [get]
bool IsOutputRedirected [get]
PauseRequest Request = new PauseRequest(null, false) [get]
bool HasRequest [get]
ConsoleKeyInfo KeyQueue [get, set]
Properties inherited from SAPTeam.Kryptor.Client.SessionHost
SessionContainer Container [get]
Gets the session container.
bool Verbose [get, protected set]
Gets the verbosity of the session host.
CancellationTokenSource MasterToken [get]
Gets the special cancellation token to use in non-standard codes. (Blocking codes outside of sessions)
Properties inherited from SAPTeam.Kryptor.Client.ISessionHost
Detailed Description
Definition at line 12 of file CliSessionHost.cs.
Constructor & Destructor Documentation
CliSessionHost()
SAPTeam.Kryptor.Cli.CliSessionHost.CliSessionHost (GlobalOptions globalOptions)
Definition at line 43 of file CliSessionHost.cs.
References SAPTeam.Kryptor.Cli.CliSessionHost.IsOutputRedirected, SAPTeam.Kryptor.Cli.CliSessionHost.NoColor, SAPTeam.Kryptor.Cli.GlobalOptions.NoColor, SAPTeam.Kryptor.Cli.CliSessionHost.NoInteractions, SAPTeam.Kryptor.Cli.CliSessionHost.Quiet, SAPTeam.Kryptor.Cli.GlobalOptions.Quiet, SAPTeam.Kryptor.Cli.GlobalOptions.Verbose, and SAPTeam.Kryptor.Client.SessionHost.Verbose.
Member Function Documentation
CreateKeyStoreLoadSession()
KeyStoreLoadSession SAPTeam.Kryptor.Cli.CliSessionHost.CreateKeyStoreLoadSession (string keyStore) [protected]
Definition at line 587 of file CliSessionHost.cs.
References SAPTeam.Kryptor.Cli.CliSessionHost.DebugLog(), SAPTeam.Kryptor.TransformerToken.IsValid(), SAPTeam.Kryptor.TransformerToken.Parse(), and SAPTeam.Kryptor.Client.SessionHost.Verbose.
Referenced by SAPTeam.Kryptor.Cli.CliSessionHost.LoadKeyStore(), and SAPTeam.Kryptor.Cli.KeyStoreAnalyze.SessionHost.Start().
DebugLog()
void SAPTeam.Kryptor.Cli.CliSessionHost.DebugLog (string message) [protected]
Definition at line 80 of file CliSessionHost.cs.
References SAPTeam.Kryptor.Client.SessionHost.Verbose.
Referenced by SAPTeam.Kryptor.Cli.CliSessionHost.CreateKeyStoreLoadSession(), SAPTeam.Kryptor.Cli.EncryptionSessionHost.Start(), SAPTeam.Kryptor.Cli.HeaderReaderSessionHost.Start(), SAPTeam.Kryptor.Cli.KeyChainReaderSessionHost.Start(), SAPTeam.Kryptor.Cli.Wordlist.InstallSessionHost.Start(), and SAPTeam.Kryptor.Cli.Wordlist.SessionHost.Start().
LoadKeyStore()
KeyStore SAPTeam.Kryptor.Cli.CliSessionHost.LoadKeyStore (string keyStore) [protected]
Definition at line 574 of file CliSessionHost.cs.
References SAPTeam.Kryptor.Cli.CliSessionHost.CreateKeyStoreLoadSession(), SAPTeam.Kryptor.Cli.KeyStoreLoadSession.KeyStore, SAPTeam.Kryptor.Client.SessionHost.NewSession(), and SAPTeam.Kryptor.Cli.CliSessionHost.ShowProgressMonitored().
Referenced by SAPTeam.Kryptor.Cli.DataProcessingSessionHost.Start().
Log()
void SAPTeam.Kryptor.Cli.CliSessionHost.Log (string message = null) [protected]
Referenced by SAPTeam.Kryptor.Cli.Wordlist.SessionHost.ListInstalledWordlists(), SAPTeam.Kryptor.Cli.CliSessionHost.Start(), SAPTeam.Kryptor.Cli.HeaderReaderSessionHost.Start(), SAPTeam.Kryptor.Cli.KeyChainReaderSessionHost.Start(), SAPTeam.Kryptor.Cli.KeyStoreGenerateSessionHost.Start(), SAPTeam.Kryptor.Cli.Wordlist.QuerySessionHost.Start(), and SAPTeam.Kryptor.Cli.Wordlist.RemoveSessionHost.Start().
LogError()
void SAPTeam.Kryptor.Cli.CliSessionHost.LogError (string message = null) [protected]
Referenced by SAPTeam.Kryptor.Cli.Wordlist.SessionHost.GetInstallationPermission(), SAPTeam.Kryptor.Cli.Wordlist.SessionHost.ListInstalledWordlists(), SAPTeam.Kryptor.Cli.CliSessionHost.Start(), SAPTeam.Kryptor.Cli.HeaderReaderSessionHost.Start(), SAPTeam.Kryptor.Cli.KeyChainReaderSessionHost.Start(), and SAPTeam.Kryptor.Cli.Wordlist.RemoveSessionHost.Start().
OnSessionRequest< TResponse >()
override async Task< TResponse > SAPTeam.Kryptor.Cli.CliSessionHost.OnSessionRequest< TResponse > (ISession session, SessionRequest< TResponse > request, CancellationToken cancellationToken)
Handles requests from the sessions.
This method should send requests to user and if it's not possible, it could return the SessionRequest<TResponse>.DefaultValue or throws an exception. The thrown exception would be catched on the sender session and the session will fail.
Parameters
session The paused session.
request The request data.
cancellationToken A cancellation token to monitor the task.
Template Parameters
TResponse The type of requested response from user.
Returns
The session host or user response.
Exceptions
NotSupportedException This exception thrown when the requested TResponse is not supported by this session host.
Implements SAPTeam.Kryptor.Client.ISessionHost.
Definition at line 617 of file CliSessionHost.cs.
ShowProgress() [1/2]
Task SAPTeam.Kryptor.Cli.CliSessionHost.ShowProgress (bool showOverall, bool showRemaining) [protected]
Definition at line 546 of file CliSessionHost.cs.
Referenced by SAPTeam.Kryptor.Cli.CliSessionHost.ShowProgressMonitored(), and SAPTeam.Kryptor.Cli.CliSessionHost.ShowProgressMonitored().
ShowProgress() [2/2]
Task SAPTeam.Kryptor.Cli.CliSessionHost.ShowProgress (SessionGroup sessionGroup) [protected]
Definition at line 560 of file CliSessionHost.cs.
ShowProgressMonitored() [1/2]
Task SAPTeam.Kryptor.Cli.CliSessionHost.ShowProgressMonitored (bool showOverall, bool showRemaining = true) [protected]
Definition at line 553 of file CliSessionHost.cs.
References SAPTeam.Kryptor.Client.SessionHost.MonitorTask(), and SAPTeam.Kryptor.Cli.CliSessionHost.ShowProgress().
Referenced by SAPTeam.Kryptor.Cli.DataProcessingSessionHost.GetSmartProgress(), SAPTeam.Kryptor.Cli.CliSessionHost.LoadKeyStore(), SAPTeam.Kryptor.Cli.KeyStoreAnalyze.SessionHost.Start(), SAPTeam.Kryptor.Cli.KeyStoreGenerateSessionHost.Start(), SAPTeam.Kryptor.Cli.Wordlist.ImportSessionHost.Start(), SAPTeam.Kryptor.Cli.Wordlist.InstallSessionHost.Start(), and SAPTeam.Kryptor.Cli.Wordlist.QuerySessionHost.Start().
ShowProgressMonitored() [2/2]
Task SAPTeam.Kryptor.Cli.CliSessionHost.ShowProgressMonitored (SessionGroup sessionGroup) [protected]
Definition at line 567 of file CliSessionHost.cs.
References SAPTeam.Kryptor.Client.SessionHost.MonitorTask(), and SAPTeam.Kryptor.Cli.CliSessionHost.ShowProgress().
Start()
override void SAPTeam.Kryptor.Cli.CliSessionHost.Start (ClientContext context)
Starts the host session in the current thread.
Parameters
context The caller context.
Implements SAPTeam.Kryptor.Client.ISessionHost.
Definition at line 53 of file CliSessionHost.cs.
References SAPTeam.Kryptor.Cli.CliSessionHost.Log(), SAPTeam.Kryptor.Cli.CliSessionHost.LogError(), SAPTeam.Kryptor.Cli.CliSessionHost.NoColor, SAPTeam.Kryptor.Cli.CliSessionHost.Quiet, and SAPTeam.Kryptor.Client.SessionHost.Verbose.
Property Documentation
HasRequest
bool SAPTeam.Kryptor.Cli.CliSessionHost.HasRequest [get]
Definition at line 24 of file CliSessionHost.cs.
IsOutputRedirected
bool SAPTeam.Kryptor.Cli.CliSessionHost.IsOutputRedirected [get]
Definition at line 20 of file CliSessionHost.cs.
Referenced by SAPTeam.Kryptor.Cli.CliSessionHost.CliSessionHost().
KeyQueue
ConsoleKeyInfo SAPTeam.Kryptor.Cli.CliSessionHost.KeyQueue [get], [set], [protected]
Definition at line 31 of file CliSessionHost.cs.
NoColor
bool SAPTeam.Kryptor.Cli.CliSessionHost.NoColor [get]
Definition at line 16 of file CliSessionHost.cs.
Referenced by SAPTeam.Kryptor.Cli.CliSessionHost.CliSessionHost(), and SAPTeam.Kryptor.Cli.CliSessionHost.Start().
NoInteractions
bool SAPTeam.Kryptor.Cli.CliSessionHost.NoInteractions [get]
Definition at line 18 of file CliSessionHost.cs.
Referenced by SAPTeam.Kryptor.Cli.CliSessionHost.CliSessionHost(), and SAPTeam.Kryptor.Cli.KeyStoreGenerateSessionHost.Start().
Quiet
bool SAPTeam.Kryptor.Cli.CliSessionHost.Quiet [get]
Definition at line 14 of file CliSessionHost.cs.
Referenced by SAPTeam.Kryptor.Cli.CliSessionHost.CliSessionHost(), and SAPTeam.Kryptor.Cli.CliSessionHost.Start().
Request
PauseRequest SAPTeam.Kryptor.Cli.CliSessionHost.Request = new PauseRequest(null, false) [get]
Definition at line 22 of file CliSessionHost.cs.
The documentation for this class was generated from the following file:
CliSessionHost.cs