SAPTeam.Kryptor.Kes Class Reference
Provides methods to encrypt and decrypt data using the Kryptor Encryption Standard (KES).
Public Member Functions
int GetDecryptionBufferSize (CryptoProcess process=default)
Gets max input buffer size for CryptoProvider.DecryptBlockAsync.
int GetEncryptionBufferSize (CryptoProcess process=default)
Gets max input buffer size for CryptoProvider.EncryptBlockAsync.
Kes(KeyStore keyStore, CryptoProviderConfiguration configuration, int blockSize=default) Kes(CryptoProvider provider, int blockSize=default) Kes (int blockSize=default)
Initializes a new instance of the Kes class with a new instance of the requested crypto provider.
async Task EncryptAsync (Stream source, Stream dest)
Encrypts the given data stream and writes the encrypted data to the destination stream.
async Task EncryptAsync (Stream source, Stream dest, CancellationToken cancellationToken)
Encrypts the given data stream and writes the encrypted data to the destination stream.
async Task EncryptAsync (Stream source, Stream dest, Header header)
Encrypts the given data stream and writes the encrypted data to the destination stream.
async Task EncryptAsync (Stream source, Stream dest, Header header, CancellationToken cancellationToken)
Encrypts the given data stream and writes the encrypted data to the destination stream.
async Task DecryptAsync (Stream source, Stream dest)
Decrypts the given data stream and writes the decrypted data to the destination data stream.
async Task DecryptAsync (Stream source, Stream dest, CancellationToken cancellationToken)
Decrypts the given data stream and writes the decrypted data to the destination data stream.
async Task< byte[]> EncryptBlockAsync (byte[] data)
Encrypts block of data asynchronously.
async Task< byte[]> EncryptBlockAsync (byte[] data, CancellationToken cancellationToken)
Encrypts block of data asynchronously.
async Task< byte[]> EncryptBlockAsync (byte[] data, CryptoProcess process)
Encrypts block of data asynchronously.
async Task< byte[]> EncryptBlockAsync (byte[] data, CryptoProcess process, CancellationToken cancellationToken)
Encrypts block of data asynchronously.
async Task< byte[]> DecryptBlockAsync (byte[] data)
Decrypts block of data asynchronously.
async Task< byte[]> DecryptBlockAsync (byte[] data, CancellationToken cancellationToken)
Decrypts block of data asynchronously.
async Task< byte[]> DecryptBlockAsync (byte[] data, CryptoProcess process)
Decrypts block of data asynchronously.
async Task< byte[]> DecryptBlockAsync (byte[] data, CryptoProcess process, CancellationToken cancellationToken)
Decrypts block of data asynchronously.
Static Public Attributes
const int DefaultBlockSize = 0x8000
Gets the default value for block size.
Properties
int BlockSize = DefaultBlockSize [get, set]
Gets or sets the block size used for buffer creation in encryption and decryption.
static Version Version [get]
Gets the version of the kes encryptor.
static Version MinimumSupportedVersion [get]
Gets the minimum supported version of the kes decryptor.
CryptoProvider Provider [get, set]
Gets or sets the crypto provider.
Events
EventHandler< double > ProgressChanged
Events inherited from SAPTeam.Kryptor.Helpers.IProgressReport
EventHandler< double > ProgressChanged
Triggered when the work progress is changed.
Detailed Description
Provides methods to encrypt and decrypt data using the Kryptor Encryption Standard (KES).
Definition at line 12 of file Kes.cs.
Constructor & Destructor Documentation
Kes()
Kes(KeyStore keyStore, CryptoProviderConfiguration configuration, int blockSize=default) Kes(CryptoProvider provider, int blockSize=default) SAPTeam.Kryptor.Kes.Kes (int blockSize = default)
Initializes a new instance of the Kes class with a new instance of the requested crypto provider.
Parameters
keyStore The keystore.
configuration The configuration to initialize crypto provider.
blockSize The block size used to read and process data.
Initializes a new instance of the Kes class.
Parameters
provider The crypto provider.
blockSize The block size used to read and process data.
Initializes a new instance of the Kes class.
Parameters
blockSize The block size used to read and process data.
Definition at line 87 of file Kes.cs.
References SAPTeam.Kryptor.Kes.BlockSize.
Member Function Documentation
DecryptAsync() [1/2]
async Task SAPTeam.Kryptor.Kes.DecryptAsync (Stream source, Stream dest)
Decrypts the given data stream and writes the decrypted data to the destination data stream.
Parameters
source The stream of encrypted data with read access.
dest The stream of destination target with write access.
Referenced by SAPTeam.Kryptor.Cli.DecryptionSession.RunAsync().
DecryptAsync() [2/2]
async Task SAPTeam.Kryptor.Kes.DecryptAsync (Stream source, Stream dest, CancellationToken cancellationToken)
Decrypts the given data stream and writes the decrypted data to the destination data stream.
Parameters
source The stream of encrypted data with read access.
dest The stream of destination target with write access.
cancellationToken The token to monitor for cancellation requests.
Definition at line 215 of file Kes.cs.
References SAPTeam.Kryptor.Header.EngineVersion, SAPTeam.Kryptor.Kes.MinimumSupportedVersion, SAPTeam.Kryptor.Header.Version, and SAPTeam.Kryptor.Kes.Version.
DecryptBlockAsync() [1/4]
async Task< byte[]> SAPTeam.Kryptor.Kes.DecryptBlockAsync (byte[] data)
Decrypts block of data asynchronously.
Parameters
data The raw encrypted data block.
Returns
Decrypted data block.
Referenced by SAPTeam.Kryptor.Kes.DecryptBlockAsync().
DecryptBlockAsync() [2/4]
async Task< byte[]> SAPTeam.Kryptor.Kes.DecryptBlockAsync (byte[] data, CancellationToken cancellationToken)
Decrypts block of data asynchronously.
Parameters
data The raw encrypted data block.
cancellationToken The token to monitor for cancellation requests.
Returns
Decrypted data block.
Definition at line 361 of file Kes.cs.
References SAPTeam.Kryptor.Kes.DecryptBlockAsync(), and SAPTeam.Kryptor.CryptoProcess.InitializeData().
DecryptBlockAsync() [3/4]
async Task< byte[]> SAPTeam.Kryptor.Kes.DecryptBlockAsync (byte[] data, CryptoProcess process)
Decrypts block of data asynchronously.
Parameters
data The raw encrypted data block.
process The crypto process data holder.
Returns
Decrypted data block.
DecryptBlockAsync() [4/4]
async Task< byte[]> SAPTeam.Kryptor.Kes.DecryptBlockAsync (byte[] data, CryptoProcess process, CancellationToken cancellationToken)
Decrypts block of data asynchronously.
Parameters
data The raw encrypted data block.
process The crypto process data holder.
cancellationToken The token to monitor for cancellation requests.
Returns
Decrypted data block.
Definition at line 389 of file Kes.cs.
References SAPTeam.Kryptor.CryptoProvider.DecryptBlockAsync(), SAPTeam.Kryptor.Kes.GetDecryptionBufferSize(), SAPTeam.Kryptor.Kes.GetEncryptionBufferSize(), and SAPTeam.Kryptor.Kes.Provider.
EncryptAsync() [1/4]
async Task SAPTeam.Kryptor.Kes.EncryptAsync (Stream source, Stream dest)
Encrypts the given data stream and writes the encrypted data to the destination stream.
Parameters
source The stream of the source data with read access.
dest The stream of destination target with write access.
EncryptAsync() [2/4]
async Task SAPTeam.Kryptor.Kes.EncryptAsync (Stream source, Stream dest, CancellationToken cancellationToken)
Encrypts the given data stream and writes the encrypted data to the destination stream.
Parameters
source The stream of the source data with read access.
dest The stream of destination target with write access.
cancellationToken The token to monitor for cancellation requests.
EncryptAsync() [3/4]
async Task SAPTeam.Kryptor.Kes.EncryptAsync (Stream source, Stream dest, Header header)
Encrypts the given data stream and writes the encrypted data to the destination stream.
Parameters
source The stream of the source data with read access.
dest The stream of destination target with write access.
header The header to write in the beginning of destination stream. if null, a new header will be created automatically.
EncryptAsync() [4/4]
async Task SAPTeam.Kryptor.Kes.EncryptAsync (Stream source, Stream dest, Header header, CancellationToken cancellationToken)
Encrypts the given data stream and writes the encrypted data to the destination stream.
Parameters
source The stream of the source data with read access.
dest The stream of destination target with write access.
header The header to write in the beginning of destination stream. if null, a new header will be created automatically.
cancellationToken The token to monitor for cancellation requests.
Definition at line 163 of file Kes.cs.
References SAPTeam.Kryptor.Header.CreatePayload(), SAPTeam.Kryptor.Kes.Provider, and SAPTeam.Kryptor.Header.Verbosity.
EncryptBlockAsync() [1/4]
async Task< byte[]> SAPTeam.Kryptor.Kes.EncryptBlockAsync (byte[] data)
Encrypts block of data asynchronously.
Parameters
data The raw data block.
Returns
Encrypted data block.
Referenced by SAPTeam.Kryptor.Kes.EncryptBlockAsync().
EncryptBlockAsync() [2/4]
async Task< byte[]> SAPTeam.Kryptor.Kes.EncryptBlockAsync (byte[] data, CancellationToken cancellationToken)
Encrypts block of data asynchronously.
Parameters
data The raw data block.
cancellationToken The token to monitor for cancellation requests.
Returns
Encrypted data block.
Definition at line 304 of file Kes.cs.
References SAPTeam.Kryptor.Kes.EncryptBlockAsync(), and SAPTeam.Kryptor.CryptoProcess.InitializeData().
EncryptBlockAsync() [3/4]
async Task< byte[]> SAPTeam.Kryptor.Kes.EncryptBlockAsync (byte[] data, CryptoProcess process)
Encrypts block of data asynchronously.
Parameters
data The raw data block.
process The crypto process data holder.
Returns
Encrypted data block.
EncryptBlockAsync() [4/4]
async Task< byte[]> SAPTeam.Kryptor.Kes.EncryptBlockAsync (byte[] data, CryptoProcess process, CancellationToken cancellationToken)
Encrypts block of data asynchronously.
Parameters
data The raw data block.
process The crypto process data holder.
cancellationToken The token to monitor for cancellation requests.
Returns
Encrypted data block.
Definition at line 332 of file Kes.cs.
References SAPTeam.Kryptor.CryptoProvider.EncryptBlockAsync(), SAPTeam.Kryptor.Kes.GetDecryptionBufferSize(), SAPTeam.Kryptor.Kes.GetEncryptionBufferSize(), and SAPTeam.Kryptor.Kes.Provider.
GetDecryptionBufferSize()
int SAPTeam.Kryptor.Kes.GetDecryptionBufferSize (CryptoProcess process = default)
Gets max input buffer size for CryptoProvider.DecryptBlockAsync.
Referenced by SAPTeam.Kryptor.Kes.DecryptBlockAsync(), and SAPTeam.Kryptor.Kes.EncryptBlockAsync().
GetEncryptionBufferSize()
int SAPTeam.Kryptor.Kes.GetEncryptionBufferSize (CryptoProcess process = default)
Gets max input buffer size for CryptoProvider.EncryptBlockAsync.
Referenced by SAPTeam.Kryptor.Kes.DecryptBlockAsync(), and SAPTeam.Kryptor.Kes.EncryptBlockAsync().
Member Data Documentation
DefaultBlockSize
const int SAPTeam.Kryptor.Kes.DefaultBlockSize = 0x8000 [static]
Gets the default value for block size.
Definition at line 19 of file Kes.cs.
Referenced by SAPTeam.Kryptor.Cli.Program.GetRootCommand().
Property Documentation
BlockSize
int SAPTeam.Kryptor.Kes.BlockSize = DefaultBlockSize [get], [set]
Gets or sets the block size used for buffer creation in encryption and decryption.
Definition at line 24 of file Kes.cs.
Referenced by SAPTeam.Kryptor.Kes.Kes().
MinimumSupportedVersion
Version SAPTeam.Kryptor.Kes.MinimumSupportedVersion [static], [get]
Gets the minimum supported version of the kes decryptor.
Definition at line 46 of file Kes.cs.
Referenced by SAPTeam.Kryptor.Kes.DecryptAsync(), and SAPTeam.Kryptor.Cli.DecryptionSession.RunAsync().
Provider
CryptoProvider SAPTeam.Kryptor.Kes.Provider [get], [set]
Gets or sets the crypto provider.
Definition at line 51 of file Kes.cs.
Referenced by SAPTeam.Kryptor.Kes.DecryptBlockAsync(), SAPTeam.Kryptor.Kes.EncryptAsync(), and SAPTeam.Kryptor.Kes.EncryptBlockAsync().
Version
Version SAPTeam.Kryptor.Kes.Version [static], [get]
Gets the version of the kes encryptor.
Definition at line 41 of file Kes.cs.
Referenced by SAPTeam.Kryptor.Kes.DecryptAsync(), and SAPTeam.Kryptor.Cli.DecryptionSession.RunAsync().
Event Documentation
ProgressChanged
EventHandler<double> SAPTeam.Kryptor.Kes.ProgressChanged
Definition at line 54 of file Kes.cs.
The documentation for this class was generated from the following file:
Kes.cs