SAPTeam.Kryptor.Client.Security.WordlistFragmentCollection Class Reference
Provides a performance-friendly wordlist lookup class.
Public Member Functions
WordlistFragmentCollection (WordlistIndexEntry entry)
Initializes a new instance of WordlistFragmentCollection class.
async Task< bool > LookupAsync (string word, CancellationToken cancellationToken)
Checks whether the word is found in the wordlist.
Static Public Member Functions
static int GetWordIdentifier (string word)
Gets the numeric fragment identifier of the given word .
Detailed Description
Provides a performance-friendly wordlist lookup class.
Definition at line 11 of file WordlistFragmentCollection.cs.
Constructor & Destructor Documentation
WordlistFragmentCollection()
SAPTeam.Kryptor.Client.Security.WordlistFragmentCollection.WordlistFragmentCollection (WordlistIndexEntry entry)
Initializes a new instance of WordlistFragmentCollection class.
Parameters
entry A valid wordlist entry.
Exceptions
DirectoryNotFoundException
Definition at line 23 of file WordlistFragmentCollection.cs.
References SAPTeam.Kryptor.Client.Security.WordlistIndexEntry.Hash, SAPTeam.Kryptor.Client.Security.WordlistIndexEntry.Id, and SAPTeam.Kryptor.Client.Security.WordlistIndexEntry.InstallDirectory.
Member Function Documentation
GetWordIdentifier()
static int SAPTeam.Kryptor.Client.Security.WordlistFragmentCollection.GetWordIdentifier (string word) [static]
Gets the numeric fragment identifier of the given word .
Parameters
word The word to calculate.
Returns
Definition at line 118 of file WordlistFragmentCollection.cs.
Referenced by SAPTeam.Kryptor.Client.Security.WordlistFragmentCollection.LookupAsync(), and SAPTeam.Kryptor.Client.Security.WordlistIndexEntry.Verify().
LookupAsync()
async Task< bool > SAPTeam.Kryptor.Client.Security.WordlistFragmentCollection.LookupAsync (string word, CancellationToken cancellationToken)
Checks whether the word is found in the wordlist.
Parameters
word Word to search.
cancellationToken The token to monitor for cancellation requests.
Returns
Definition at line 49 of file WordlistFragmentCollection.cs.
References SAPTeam.Kryptor.Client.Security.WordlistFragmentCollection.GetWordIdentifier(), and SAPTeam.Kryptor.Client.Security.WordlistIndexEntry.InstallDirectory.
Referenced by SAPTeam.Kryptor.Cli.Wordlist.QuerySession.RunAsync().
The documentation for this class was generated from the following file:
WordlistFragmentCollection.cs