SAPTeam.Kryptor.Cli.KeyChainReaderSessionHost Class Reference
Public Member Functions
KeyChainReaderSessionHost (GlobalOptions globalOptions, string keyChainPath, string filePath)
override void Start (ClientContext context)
Starts the host session in the current thread.
Public Member Functions inherited from SAPTeam.Kryptor.Cli.CliSessionHost
CliSessionHost (GlobalOptions globalOptions)
override void Start (ClientContext context)
Starts the host session in the current thread.
override async Task< TResponse > OnSessionRequest< TResponse > (ISession session, SessionRequest< TResponse > request, CancellationToken cancellationToken)
Handles requests from the sessions.
Public Member Functions inherited from SAPTeam.Kryptor.Client.SessionHost
void Start (ClientContext context)
Starts the host session in the current thread.
Parameters
context The caller context.
virtual void End (bool cancelled)
Ends the host session.
Parameters
cancelled Whether the host session ending triggered by cancel request.
virtual void NewSession (ISession session, bool autoRemove=false, bool autoStart=true)
Starts a new session in this session host.
Parameters
session A session with status SessionStatus.NotStarted.
autoRemove Determines whether to automatically remove session after end.
autoStart Determines whether to automatically call the session manager to start this session.
virtual void MonitorTask (Task task)
Adds given task to the task pool and be monitored by the session host.
Parameters
task The task to be monitored.
Task< TResponse > OnSessionRequest< TResponse > (ISession session, SessionRequest< TResponse > request, CancellationToken cancellationToken)
Handles requests from the sessions.
This method should send requests to user and if it's not possible, it could return the SessionRequest<TResponse>.DefaultValue or throws an exception. The thrown exception would be catched on the sender session and the session will fail.
Public Member Functions inherited from SAPTeam.Kryptor.Client.ISessionHost
Public Attributes
string KeyChainPath
string FilePath
Additional Inherited Members
Protected Member Functions inherited from SAPTeam.Kryptor.Cli.CliSessionHost
void Log (string message=null)
void LogError (string message=null)
void DebugLog (string message)
Task ShowProgress (bool showOverall, bool showRemaining)
Task ShowProgressMonitored (bool showOverall, bool showRemaining=true)
Task ShowProgress (SessionGroup sessionGroup)
Task ShowProgressMonitored (SessionGroup sessionGroup)
KeyStore LoadKeyStore (string keyStore)
KeyStoreLoadSession CreateKeyStoreLoadSession (string keyStore)
Protected Member Functions inherited from SAPTeam.Kryptor.Client.SessionHost
SessionHost ()
Initializes all SessionHost instances.
Properties inherited from SAPTeam.Kryptor.Cli.CliSessionHost
bool Quiet [get]
bool NoColor [get]
bool NoInteractions [get]
bool IsOutputRedirected [get]
PauseRequest Request = new PauseRequest(null, false) [get]
bool HasRequest [get]
ConsoleKeyInfo KeyQueue [get, set]
Properties inherited from SAPTeam.Kryptor.Client.SessionHost
SessionContainer Container [get]
Gets the session container.
bool Verbose [get, protected set]
Gets the verbosity of the session host.
CancellationTokenSource MasterToken [get]
Gets the special cancellation token to use in non-standard codes. (Blocking codes outside of sessions)
Properties inherited from SAPTeam.Kryptor.Client.ISessionHost
Detailed Description
Definition at line 5 of file KeyChainReaderSessionHost.cs.
Constructor & Destructor Documentation
KeyChainReaderSessionHost()
SAPTeam.Kryptor.Cli.KeyChainReaderSessionHost.KeyChainReaderSessionHost (GlobalOptions globalOptions, string keyChainPath, string filePath)
Definition at line 10 of file KeyChainReaderSessionHost.cs.
References SAPTeam.Kryptor.Cli.KeyChainReaderSessionHost.FilePath, and SAPTeam.Kryptor.Cli.KeyChainReaderSessionHost.KeyChainPath.
Member Function Documentation
Start()
override void SAPTeam.Kryptor.Cli.KeyChainReaderSessionHost.Start (ClientContext context)
Starts the host session in the current thread.
Parameters
context The caller context.
Implements SAPTeam.Kryptor.Client.ISessionHost.
Definition at line 16 of file KeyChainReaderSessionHost.cs.
References SAPTeam.Kryptor.Cli.CliSessionHost.DebugLog(), SAPTeam.Kryptor.Cli.KeyChainReaderSessionHost.FilePath, SAPTeam.Kryptor.Client.KeyChainCollection.FilePath, SAPTeam.Kryptor.Client.KeyChain.Fingerprint, SAPTeam.Kryptor.Cli.KeyChainReaderSessionHost.KeyChainPath, SAPTeam.Kryptor.Cli.CliSessionHost.Log(), SAPTeam.Kryptor.Cli.CliSessionHost.LogError(), SAPTeam.Kryptor.Client.ClientHeader.Serial, and SAPTeam.Kryptor.Client.KeyChain.TransformerToken.
Member Data Documentation
FilePath
string SAPTeam.Kryptor.Cli.KeyChainReaderSessionHost.FilePath
Definition at line 8 of file KeyChainReaderSessionHost.cs.
Referenced by SAPTeam.Kryptor.Cli.KeyChainReaderSessionHost.KeyChainReaderSessionHost(), and SAPTeam.Kryptor.Cli.KeyChainReaderSessionHost.Start().
KeyChainPath
string SAPTeam.Kryptor.Cli.KeyChainReaderSessionHost.KeyChainPath
Definition at line 7 of file KeyChainReaderSessionHost.cs.
Referenced by SAPTeam.Kryptor.Cli.KeyChainReaderSessionHost.KeyChainReaderSessionHost(), and SAPTeam.Kryptor.Cli.KeyChainReaderSessionHost.Start().
The documentation for this class was generated from the following file:
KeyChainReaderSessionHost.cs