SAPTeam.Kryptor.Cli.EncryptionSessionHost Class Reference
Public Member Functions
EncryptionSessionHost (GlobalOptions globalOptions, DataProcessingOptions options, int hVerbose, string keyChainPath, bool obfuscate)
override void Start (ClientContext context)
Starts the host session in the current thread.
Public Member Functions inherited from SAPTeam.Kryptor.Cli.DataProcessingSessionHost
DataProcessingSessionHost (GlobalOptions globalOptions, DataProcessingOptions options)
override void Start (ClientContext context)
Starts the host session in the current thread.
Task GetSmartProgress (SessionGroup sessionGroup)
void EnumerateFiles (Action< string, string > action)
Public Member Functions inherited from SAPTeam.Kryptor.Cli.CliSessionHost
CliSessionHost (GlobalOptions globalOptions)
override void Start (ClientContext context)
Starts the host session in the current thread.
override async Task< TResponse > OnSessionRequest< TResponse > (ISession session, SessionRequest< TResponse > request, CancellationToken cancellationToken)
Handles requests from the sessions.
Public Member Functions inherited from SAPTeam.Kryptor.Client.SessionHost
void Start (ClientContext context)
Starts the host session in the current thread.
Parameters
context The caller context.
virtual void End (bool cancelled)
Ends the host session.
Parameters
cancelled Whether the host session ending triggered by cancel request.
virtual void NewSession (ISession session, bool autoRemove=false, bool autoStart=true)
Starts a new session in this session host.
Parameters
session A session with status SessionStatus.NotStarted.
autoRemove Determines whether to automatically remove session after end.
autoStart Determines whether to automatically call the session manager to start this session.
virtual void MonitorTask (Task task)
Adds given task to the task pool and be monitored by the session host.
Parameters
task The task to be monitored.
Task< TResponse > OnSessionRequest< TResponse > (ISession session, SessionRequest< TResponse > request, CancellationToken cancellationToken)
Handles requests from the sessions.
This method should send requests to user and if it's not possible, it could return the SessionRequest<TResponse>.DefaultValue or throws an exception. The thrown exception would be catched on the sender session and the session will fail.
Public Member Functions inherited from SAPTeam.Kryptor.Client.ISessionHost
Properties
int HeaderVerbosity [get]
string KeyChainPath [get]
bool UseKeyChain [get]
KeyChainCollection KeyChainCollection [get]
bool Obfuscate [get]
Properties inherited from SAPTeam.Kryptor.Cli.DataProcessingSessionHost
int BlockSize [get]
CryptoProviderConfiguration Configuration [get]
string OutputPath [get]
KeyStore KeyStore [get]
Properties inherited from SAPTeam.Kryptor.Cli.CliSessionHost
bool Quiet [get]
bool NoColor [get]
bool NoInteractions [get]
bool IsOutputRedirected [get]
PauseRequest Request = new PauseRequest(null, false) [get]
bool HasRequest [get]
ConsoleKeyInfo KeyQueue [get, set]
Properties inherited from SAPTeam.Kryptor.Client.SessionHost
SessionContainer Container [get]
Gets the session container.
bool Verbose [get, protected set]
Gets the verbosity of the session host.
CancellationTokenSource MasterToken [get]
Gets the special cancellation token to use in non-standard codes. (Blocking codes outside of sessions)
Properties inherited from SAPTeam.Kryptor.Client.ISessionHost
Additional Inherited Members
Static Public Member Functions inherited from SAPTeam.Kryptor.Cli.DataProcessingSessionHost
static string GetRelativePath (string relativeTo, string path)
Public Attributes inherited from SAPTeam.Kryptor.Cli.DataProcessingSessionHost
readonly string KeystoreString
Protected Member Functions inherited from SAPTeam.Kryptor.Cli.CliSessionHost
void Log (string message=null)
void LogError (string message=null)
void DebugLog (string message)
Task ShowProgress (bool showOverall, bool showRemaining)
Task ShowProgressMonitored (bool showOverall, bool showRemaining=true)
Task ShowProgress (SessionGroup sessionGroup)
Task ShowProgressMonitored (SessionGroup sessionGroup)
KeyStore LoadKeyStore (string keyStore)
KeyStoreLoadSession CreateKeyStoreLoadSession (string keyStore)
Protected Member Functions inherited from SAPTeam.Kryptor.Client.SessionHost
SessionHost ()
Initializes all SessionHost instances.
Detailed Description
Definition at line 5 of file EncryptionSessionHost.cs.
Constructor & Destructor Documentation
EncryptionSessionHost()
SAPTeam.Kryptor.Cli.EncryptionSessionHost.EncryptionSessionHost (GlobalOptions globalOptions, DataProcessingOptions options, int hVerbose, string keyChainPath, bool obfuscate)
Definition at line 13 of file EncryptionSessionHost.cs.
References SAPTeam.Kryptor.Cli.EncryptionSessionHost.KeyChainPath, SAPTeam.Kryptor.Cli.EncryptionSessionHost.Obfuscate, and SAPTeam.Kryptor.Cli.EncryptionSessionHost.UseKeyChain.
Member Function Documentation
Start()
override void SAPTeam.Kryptor.Cli.EncryptionSessionHost.Start (ClientContext context)
Starts the host session in the current thread.
Parameters
context The caller context.
Implements SAPTeam.Kryptor.Client.ISessionHost.
Definition at line 21 of file EncryptionSessionHost.cs.
References SAPTeam.Kryptor.Cli.DataProcessingSessionHost.BlockSize, SAPTeam.Kryptor.Cli.DataProcessingSessionHost.Configuration, SAPTeam.Kryptor.Client.SessionHost.Container, SAPTeam.Kryptor.Cli.CliSessionHost.DebugLog(), SAPTeam.Kryptor.Cli.DataProcessingSessionHost.EnumerateFiles(), SAPTeam.Kryptor.Cli.DataProcessingSessionHost.GetSmartProgress(), SAPTeam.Kryptor.Cli.EncryptionSessionHost.KeyChainCollection, SAPTeam.Kryptor.Cli.EncryptionSessionHost.KeyChainPath, SAPTeam.Kryptor.Client.SessionHost.NewSession(), SAPTeam.Kryptor.Client.KeyChainCollection.Save(), SAPTeam.Kryptor.Client.SessionContainer.SetSessionGroup(), SAPTeam.Kryptor.Client.SessionContainer.StartQueuedSessions(), and SAPTeam.Kryptor.Cli.EncryptionSessionHost.UseKeyChain.
Property Documentation
HeaderVerbosity
int SAPTeam.Kryptor.Cli.EncryptionSessionHost.HeaderVerbosity [get]
Definition at line 7 of file EncryptionSessionHost.cs.
KeyChainCollection
KeyChainCollection SAPTeam.Kryptor.Cli.EncryptionSessionHost.KeyChainCollection [get]
Definition at line 10 of file EncryptionSessionHost.cs.
Referenced by SAPTeam.Kryptor.Cli.EncryptionSession.RunAsync(), and SAPTeam.Kryptor.Cli.EncryptionSessionHost.Start().
KeyChainPath
string SAPTeam.Kryptor.Cli.EncryptionSessionHost.KeyChainPath [get]
Definition at line 8 of file EncryptionSessionHost.cs.
Referenced by SAPTeam.Kryptor.Cli.EncryptionSessionHost.EncryptionSessionHost(), and SAPTeam.Kryptor.Cli.EncryptionSessionHost.Start().
Obfuscate
bool SAPTeam.Kryptor.Cli.EncryptionSessionHost.Obfuscate [get]
Definition at line 11 of file EncryptionSessionHost.cs.
Referenced by SAPTeam.Kryptor.Cli.EncryptionSessionHost.EncryptionSessionHost(), and SAPTeam.Kryptor.Cli.EncryptionSession.RunAsync().
UseKeyChain
bool SAPTeam.Kryptor.Cli.EncryptionSessionHost.UseKeyChain [get]
Definition at line 9 of file EncryptionSessionHost.cs.
Referenced by SAPTeam.Kryptor.Cli.EncryptionSessionHost.EncryptionSessionHost(), SAPTeam.Kryptor.Cli.EncryptionSession.RunAsync(), and SAPTeam.Kryptor.Cli.EncryptionSessionHost.Start().
The documentation for this class was generated from the following file:
EncryptionSessionHost.cs