SAPTeam.Kryptor.Client.Security.WordlistIndexEntry Class Reference
Represents schema to store and retrive wordlist informations.
Public Member Functions
WordlistFragmentCollection Open ()
Opens the wordlist with WordlistFragmentCollection.
WordlistVerificationMetadata[] GetMetadata ()
Gets the metadata array of this wordlist.
bool CheckBasicValidity (bool throwException=false)
Checks basic validity of this instance, includes valid id and hash.
bool CheckInstallation (bool throwException=false)
Checks validity of the wordlist installation.
bool Verify (bool throwException=false)
Verifies integrity and compatibility of the wordlist and it's fragments.
Properties
string Id [get, set]
Gets or sets the identifier of the wordlist.
string Name [get, set]
Gets or sets the user-friendly name of the wordlist.
Uri Uri [get, set]
Gets or sets the URI used to download the wordlist.
byte[] Hash [get, set]
Gets or sets the SHA256 hash of the wordlist.
bool Enforced [get, set]
Gets or sets the enforcement status of the wordlist. if it's true, it will block any operations if the word is found in the wordlist, but if set to false, it just shows a warning.
bool Compressed [get, set]
Gets or sets the compressed status of the wordlist file. if it's true, the downloader will try to decompress it, otherwise it will be processed as is.
bool Optimized [get, set]
Gets or sets the optimization status of the wordlist file. if it's true, it means that the wordlist is optimized by fragment compiler and all duplicated entries are removed, otherwise it means that the wordlist is not optimized and may be have some duplicated entries.
string InstallDirectory [get, set]
Gets or sets the install directory of thw wordlist.
long Lines [get, set]
Gets or sets the number of lines in this wordlist.
long Words [get, set]
Gets or sets the number of actual words in this wordlist.
long Size [get, set]
Gets or sets the wordlist file size.
Detailed Description
Represents schema to store and retrive wordlist informations.
Definition at line 8 of file WordlistIndexEntry.cs.
Member Function Documentation
CheckBasicValidity()
bool SAPTeam.Kryptor.Client.Security.WordlistIndexEntry.CheckBasicValidity (bool throwException = false)
Checks basic validity of this instance, includes valid id and hash.
Parameters
throwException if true, the method will throw exception when any of the checking items were failed. otherwise it just returns the validation result as bool.
Returns
true if validation were passed. otherwise it will return false.
Exceptions
InvalidDataException
Definition at line 111 of file WordlistIndexEntry.cs.
References SAPTeam.Kryptor.Client.Security.WordlistIndexEntry.Hash, and SAPTeam.Kryptor.Client.Security.WordlistIndexEntry.Id.
Referenced by SAPTeam.Kryptor.Client.Security.WordlistIndexEntry.Open(), and SAPTeam.Kryptor.Client.Security.WordlistIndexEntry.Verify().
CheckInstallation()
bool SAPTeam.Kryptor.Client.Security.WordlistIndexEntry.CheckInstallation (bool throwException = false)
Checks validity of the wordlist installation.
Parameters
throwException if true, the method will throw exception when any of the checking items were failed. otherwise it just returns the validation result as bool.
Returns
true if validation were passed. otherwise it will return false.
Exceptions
ApplicationException
DirectoryNotFoundException
InvalidDataException
FileNotFoundException
Definition at line 142 of file WordlistIndexEntry.cs.
References SAPTeam.Kryptor.Client.Security.WordlistIndexEntry.InstallDirectory.
Referenced by SAPTeam.Kryptor.Client.Security.WordlistIndexEntry.Open(), and SAPTeam.Kryptor.Client.Security.WordlistIndexEntry.Verify().
GetMetadata()
WordlistVerificationMetadata[] SAPTeam.Kryptor.Client.Security.WordlistIndexEntry.GetMetadata ()
Gets the metadata array of this wordlist.
Returns
An array contains the metadata for all fragments.
Definition at line 87 of file WordlistIndexEntry.cs.
Referenced by SAPTeam.Kryptor.Client.Security.WordlistIndexEntry.Verify().
Open()
WordlistFragmentCollection SAPTeam.Kryptor.Client.Security.WordlistIndexEntry.Open ()
Opens the wordlist with WordlistFragmentCollection.
Returns
A new instance of the WordlistFragmentCollection class initialized with this wordlist.
Definition at line 73 of file WordlistIndexEntry.cs.
References SAPTeam.Kryptor.Client.Security.WordlistIndexEntry.CheckBasicValidity(), and SAPTeam.Kryptor.Client.Security.WordlistIndexEntry.CheckInstallation().
Verify()
bool SAPTeam.Kryptor.Client.Security.WordlistIndexEntry.Verify (bool throwException = false)
Verifies integrity and compatibility of the wordlist and it's fragments.
This method also calls the both CheckBasicValidity(bool) and CheckInstallation(bool) methods.
Parameters
throwException if true, the method will throw exception when any of the checking items were failed. otherwise it just returns the validation result as bool.
Returns
true if validation were passed. otherwise it will return false.
Exceptions
InvalidDataException
Definition at line 183 of file WordlistIndexEntry.cs.
References SAPTeam.Kryptor.Client.Security.WordlistIndexEntry.CheckBasicValidity(), SAPTeam.Kryptor.Client.Security.WordlistIndexEntry.CheckInstallation(), SAPTeam.Kryptor.Client.Security.WordlistVerificationMetadata.Checksum, SAPTeam.Kryptor.Client.Security.WordlistVerificationMetadata.FragmentId, SAPTeam.Kryptor.Client.Security.WordlistIndexEntry.GetMetadata(), SAPTeam.Kryptor.Client.Security.WordlistFragmentCollection.GetWordIdentifier(), SAPTeam.Kryptor.Client.Security.WordlistIndexEntry.Hash, SAPTeam.Kryptor.Client.Security.WordlistIndexEntry.InstallDirectory, and SAPTeam.Kryptor.Client.Security.WordlistVerificationMetadata.LookupString.
Property Documentation
Compressed
bool SAPTeam.Kryptor.Client.Security.WordlistIndexEntry.Compressed [get], [set]
Gets or sets the compressed status of the wordlist file. if it's true, the downloader will try to decompress it, otherwise it will be processed as is.
Definition at line 40 of file WordlistIndexEntry.cs.
Enforced
bool SAPTeam.Kryptor.Client.Security.WordlistIndexEntry.Enforced [get], [set]
Gets or sets the enforcement status of the wordlist. if it's true, it will block any operations if the word is found in the wordlist, but if set to false, it just shows a warning.
Definition at line 35 of file WordlistIndexEntry.cs.
Referenced by SAPTeam.Kryptor.Cli.Wordlist.InstallSessionHost.Start().
Hash
byte [] SAPTeam.Kryptor.Client.Security.WordlistIndexEntry.Hash [get], [set]
Gets or sets the SHA256 hash of the wordlist.
Definition at line 30 of file WordlistIndexEntry.cs.
Referenced by SAPTeam.Kryptor.Client.Security.WordlistIndex.Add(), SAPTeam.Kryptor.Client.Security.WordlistIndexEntry.CheckBasicValidity(), SAPTeam.Kryptor.Cli.Wordlist.SessionHost.GetInstallationPermission(), SAPTeam.Kryptor.Client.Security.WordlistIndexEntry.Verify(), and SAPTeam.Kryptor.Client.Security.WordlistFragmentCollection.WordlistFragmentCollection().
Id
string SAPTeam.Kryptor.Client.Security.WordlistIndexEntry.Id [get], [set]
Gets or sets the identifier of the wordlist.
Definition at line 15 of file WordlistIndexEntry.cs.
Referenced by SAPTeam.Kryptor.Client.Security.WordlistIndex.Add(), SAPTeam.Kryptor.Client.Security.WordlistIndexEntry.CheckBasicValidity(), SAPTeam.Kryptor.Cli.Wordlist.SessionHost.GetInstallationPermission(), and SAPTeam.Kryptor.Client.Security.WordlistFragmentCollection.WordlistFragmentCollection().
InstallDirectory
string SAPTeam.Kryptor.Client.Security.WordlistIndexEntry.InstallDirectory [get], [set]
Gets or sets the install directory of thw wordlist.
Definition at line 50 of file WordlistIndexEntry.cs.
Referenced by SAPTeam.Kryptor.Client.Security.WordlistIndexEntry.CheckInstallation(), SAPTeam.Kryptor.Client.Security.WordlistFragmentCollection.LookupAsync(), SAPTeam.Kryptor.Cli.Wordlist.SessionHost.RemoveWordlist(), SAPTeam.Kryptor.Client.Security.WordlistIndexEntry.Verify(), and SAPTeam.Kryptor.Client.Security.WordlistFragmentCollection.WordlistFragmentCollection().
Lines
long SAPTeam.Kryptor.Client.Security.WordlistIndexEntry.Lines [get], [set]
Gets or sets the number of lines in this wordlist.
Definition at line 55 of file WordlistIndexEntry.cs.
Name
string SAPTeam.Kryptor.Client.Security.WordlistIndexEntry.Name [get], [set]
Gets or sets the user-friendly name of the wordlist.
Definition at line 20 of file WordlistIndexEntry.cs.
Optimized
bool SAPTeam.Kryptor.Client.Security.WordlistIndexEntry.Optimized [get], [set]
Gets or sets the optimization status of the wordlist file. if it's true, it means that the wordlist is optimized by fragment compiler and all duplicated entries are removed, otherwise it means that the wordlist is not optimized and may be have some duplicated entries.
Definition at line 45 of file WordlistIndexEntry.cs.
Size
long SAPTeam.Kryptor.Client.Security.WordlistIndexEntry.Size [get], [set]
Gets or sets the wordlist file size.
Definition at line 65 of file WordlistIndexEntry.cs.
Uri
Uri SAPTeam.Kryptor.Client.Security.WordlistIndexEntry.Uri [get], [set]
Gets or sets the URI used to download the wordlist.
Definition at line 25 of file WordlistIndexEntry.cs.
Words
long SAPTeam.Kryptor.Client.Security.WordlistIndexEntry.Words [get], [set]
Gets or sets the number of actual words in this wordlist.
Definition at line 60 of file WordlistIndexEntry.cs.
The documentation for this class was generated from the following file:
WordlistIndexEntry.cs