SAPTeam.Kryptor.Client.ClientContext Class Reference
Provides an application context with session based design model.
Public Member Functions
void NewSessionHost (ISessionHost host)
Starts a new session host.
Protected Member Functions
override void CreateContext ()
override void DisposeContext ()
virtual void StartSessionHost ()
Starts the session host.
Properties
static Version EngineVersion = new Version(Assembly.GetAssembly(typeof(Kes)).GetCustomAttribute<AssemblyFileVersionAttribute>().Version) [get]
Gets the version of the kryptor engine.
static Version ClientVersion = new Version(Assembly.GetAssembly(typeof(ClientContext)).GetCustomAttribute<AssemblyFileVersionAttribute>().Version) [get]
Gets the version of the kryptor client front-end.
ISessionHost Host [get]
Gets the application session host.
Detailed Description
Provides an application context with session based design model.
Definition at line 11 of file ClientContext.cs.
Member Function Documentation
CreateContext()
override void SAPTeam.Kryptor.Client.ClientContext.CreateContext () [protected]
Definition at line 31 of file ClientContext.cs.
References SAPTeam.Kryptor.Generators.EntroX.AddEntropy().
DisposeContext()
override void SAPTeam.Kryptor.Client.ClientContext.DisposeContext () [protected]
NewSessionHost()
void SAPTeam.Kryptor.Client.ClientContext.NewSessionHost (ISessionHost host)
Starts a new session host.
Parameters
host An instance of ISessionHost to control the program.
Definition at line 48 of file ClientContext.cs.
References SAPTeam.Kryptor.Client.ISessionHost.End(), SAPTeam.Kryptor.Client.ClientContext.Host, and SAPTeam.Kryptor.Client.ClientContext.StartSessionHost().
StartSessionHost()
virtual void SAPTeam.Kryptor.Client.ClientContext.StartSessionHost () [protected], [virtual]
Starts the session host.
Reimplemented in SAPTeam.Kryptor.Cli.CliContext.
Referenced by SAPTeam.Kryptor.Client.ClientContext.NewSessionHost().
Property Documentation
ClientVersion
Version SAPTeam.Kryptor.Client.ClientContext.ClientVersion = new Version(Assembly.GetAssembly(typeof(ClientContext)).GetCustomAttribute<AssemblyFileVersionAttribute>().Version) [static], [get]
Gets the version of the kryptor client front-end.
Definition at line 21 of file ClientContext.cs.
EngineVersion
Version SAPTeam.Kryptor.Client.ClientContext.EngineVersion = new Version(Assembly.GetAssembly(typeof(Kes)).GetCustomAttribute<AssemblyFileVersionAttribute>().Version) [static], [get]
Gets the version of the kryptor engine.
Definition at line 16 of file ClientContext.cs.
Host
ISessionHost SAPTeam.Kryptor.Client.ClientContext.Host [get]
Gets the application session host.
Definition at line 28 of file ClientContext.cs.
Referenced by SAPTeam.Kryptor.Client.ClientContext.NewSessionHost().
The documentation for this class was generated from the following file:
ClientContext.cs