SAPTeam.Kryptor.CryptoProvider Class Reference
Represents the abstract base class for KES Crypto Providers.
Public Member Functions
virtual async Task< byte[]> EncryptBlockAsync (byte[] data, CryptoProcess process, CancellationToken cancellationToken)
Encrypts block of data asynchronously.
virtual async Task< byte[]> DecryptBlockAsync (byte[] data, CryptoProcess process, CancellationToken cancellationToken)
Decrypts block of data asynchronously.
object Clone ()
Protected Member Functions
virtual void ApplyHeader (KeyStore keyStore, CryptoProviderConfiguration configuration=null)
Initializes a new crypto provider.
Task< IEnumerable< byte > > EncryptChunkAsync (byte[] chunk, CryptoProcess process, CancellationToken cancellationToken)
Encrypts chunk of data asynchronously.
Task< IEnumerable< byte > > DecryptChunkAsync (byte[] chunk, CryptoProcess process, CancellationToken cancellationToken)
Decrypts chunk of data asynchronously.
Properties
virtual int DecryptionChunkSize [get]
Gets the Decryption Chunk Size.
virtual int EncryptionChunkSize [get]
Gets the Encryption Chunk Size.
CryptoProviderConfiguration Configuration [get]
Gets the configuration of this crypto provider instance.
KeyStore KeyStore [get]
Gets the keystore for crypto operations.
Detailed Description
Represents the abstract base class for KES Crypto Providers.
Definition at line 10 of file CryptoProvider.cs.
Member Function Documentation
ApplyHeader()
virtual void SAPTeam.Kryptor.CryptoProvider.ApplyHeader (KeyStore keyStore, CryptoProviderConfiguration configuration = null) [protected], [virtual]
Initializes a new crypto provider.
Parameters
keyStore The keystore with at least 2 keys.
configuration The configuration to initialize the crypto provider
Reimplemented in SAPTeam.Kryptor.CryptoProviders.TransformedKey, and SAPTeam.Kryptor.CryptoProviders.TransformedParameters.
Definition at line 90 of file CryptoProvider.cs.
References SAPTeam.Kryptor.CryptoProvider.Configuration.
Clone()
object SAPTeam.Kryptor.CryptoProvider.Clone ()
DecryptBlockAsync()
virtual async Task< byte[]> SAPTeam.Kryptor.CryptoProvider.DecryptBlockAsync (byte[] data, CryptoProcess process, CancellationToken cancellationToken) [virtual]
Decrypts block of data asynchronously.
Parameters
data The raw encrypted data block.
process The crypto process data holder.
cancellationToken The token to monitor for cancellation requests.
Returns
Decrypted data block.
Reimplemented in SAPTeam.Kryptor.CryptoProviders.DynamicEncryption.
Definition at line 142 of file CryptoProvider.cs.
References SAPTeam.Kryptor.CryptoProcess.BlockIndex, SAPTeam.Kryptor.CryptoProcess.ChunkIndex, SAPTeam.Kryptor.CryptoProvider.Configuration, SAPTeam.Kryptor.CryptoProvider.DecryptChunkAsync(), SAPTeam.Kryptor.CryptoProvider.DecryptionChunkSize, SAPTeam.Kryptor.CryptoProviderConfiguration.DynamicBlockProccessing, and SAPTeam.Kryptor.CryptoProviderConfiguration.RemoveHash.
Referenced by SAPTeam.Kryptor.Kes.DecryptBlockAsync().
DecryptChunkAsync()
Task< IEnumerable< byte > > SAPTeam.Kryptor.CryptoProvider.DecryptChunkAsync (byte[] chunk, CryptoProcess process, CancellationToken cancellationToken) [abstract], [protected]
Decrypts chunk of data asynchronously.
Parameters
chunk The raw encrypted data chunk.
process The crypto process data holder.
cancellationToken The token to monitor for cancellation requests.
Returns
Decrypted data chunk.
Referenced by SAPTeam.Kryptor.CryptoProvider.DecryptBlockAsync().
EncryptBlockAsync()
virtual async Task< byte[]> SAPTeam.Kryptor.CryptoProvider.EncryptBlockAsync (byte[] data, CryptoProcess process, CancellationToken cancellationToken) [virtual]
Encrypts block of data asynchronously.
Parameters
data The raw data block.
process The crypto process data holder.
cancellationToken The token to monitor for cancellation requests.
Returns
Encrypted data block.
Reimplemented in SAPTeam.Kryptor.CryptoProviders.DynamicEncryption.
Definition at line 108 of file CryptoProvider.cs.
References SAPTeam.Kryptor.CryptoProcess.BlockHash, SAPTeam.Kryptor.CryptoProcess.BlockIndex, SAPTeam.Kryptor.CryptoProcess.ChunkIndex, SAPTeam.Kryptor.CryptoProvider.Configuration, SAPTeam.Kryptor.CryptoProviderConfiguration.DynamicBlockProccessing, SAPTeam.Kryptor.CryptoProvider.EncryptChunkAsync(), and SAPTeam.Kryptor.CryptoProvider.EncryptionChunkSize.
Referenced by SAPTeam.Kryptor.Kes.EncryptBlockAsync().
EncryptChunkAsync()
Task< IEnumerable< byte > > SAPTeam.Kryptor.CryptoProvider.EncryptChunkAsync (byte[] chunk, CryptoProcess process, CancellationToken cancellationToken) [abstract], [protected]
Encrypts chunk of data asynchronously.
Parameters
chunk The raw data chunk.
process The crypto process data holder.
cancellationToken The token to monitor for cancellation requests.
Returns
Encrypted data chunk.
Referenced by SAPTeam.Kryptor.CryptoProvider.EncryptBlockAsync().
Property Documentation
Configuration
CryptoProviderConfiguration SAPTeam.Kryptor.CryptoProvider.Configuration [get]
Gets the configuration of this crypto provider instance.
Definition at line 27 of file CryptoProvider.cs.
Referenced by SAPTeam.Kryptor.CryptoProvider.ApplyHeader(), SAPTeam.Kryptor.CryptoProviders.TransformedKey.ApplyHeader(), SAPTeam.Kryptor.CryptoProviders.TransformedParameters.ApplyHeader(), SAPTeam.Kryptor.CryptoProvider.DecryptBlockAsync(), and SAPTeam.Kryptor.CryptoProvider.EncryptBlockAsync().
DecryptionChunkSize
virtual int SAPTeam.Kryptor.CryptoProvider.DecryptionChunkSize [get]
Gets the Decryption Chunk Size.
Definition at line 15 of file CryptoProvider.cs.
Referenced by SAPTeam.Kryptor.CryptoProvider.DecryptBlockAsync().
EncryptionChunkSize
virtual int SAPTeam.Kryptor.CryptoProvider.EncryptionChunkSize [get]
Gets the Encryption Chunk Size.
Definition at line 20 of file CryptoProvider.cs.
Referenced by SAPTeam.Kryptor.CryptoProvider.EncryptBlockAsync().
KeyStore
KeyStore SAPTeam.Kryptor.CryptoProvider.KeyStore [get]
Gets the keystore for crypto operations.
Definition at line 47 of file CryptoProvider.cs.
The documentation for this class was generated from the following file:
CryptoProvider.cs