SAPTeam.Kryptor.KeyStore Struct Reference
Stores keys for the Kes class.
Public Member Functions
KeyStore (byte[] bytes)
Initializes a new instance of the KeyStore struct.
Static Public Member Functions
static KeyStore Generate (int count=0)
Initializes a new KeyStore instance with random key.
static int GetRandomOddNumber ()
Returns a random odd number between 257 and 2047.
Properties
byte[] this[int index] [get]
Gets the key at the specified index.
byte[][] Keys [get]
Gets the keys to store.
byte[] Raw [get]
Gets the raw flat bytes array of data.
byte[] Fingerprint [get]
Gets the unique fingerprint of this keystore.
Detailed Description
Stores keys for the Kes class.
Definition at line 9 of file KeyStore.cs.
Constructor & Destructor Documentation
KeyStore()
SAPTeam.Kryptor.KeyStore.KeyStore (byte[] bytes)
Initializes a new instance of the KeyStore struct.
Parameters
bytes The keys to store.
Definition at line 45 of file KeyStore.cs.
References SAPTeam.Kryptor.KeyStore.Fingerprint, SAPTeam.Kryptor.KeyStore.Keys, and SAPTeam.Kryptor.KeyStore.Raw.
Referenced by SAPTeam.Kryptor.KeyStore.Generate().
Member Function Documentation
Generate()
static KeyStore SAPTeam.Kryptor.KeyStore.Generate (int count = 0) [static]
Initializes a new KeyStore instance with random key.
Parameters
count The number of keys to generate.
Returns
The new KeyStore instance.
Definition at line 66 of file KeyStore.cs.
References SAPTeam.Kryptor.Generators.SafeRng.Generate(), SAPTeam.Kryptor.KeyStore.GetRandomOddNumber(), and SAPTeam.Kryptor.KeyStore.KeyStore().
GetRandomOddNumber()
static int SAPTeam.Kryptor.KeyStore.GetRandomOddNumber () [static]
Returns a random odd number between 257 and 2047.
Returns
Definition at line 83 of file KeyStore.cs.
Referenced by SAPTeam.Kryptor.KeyStore.Generate(), and SAPTeam.Kryptor.Cli.KeyStoreGenerateSessionHost.KeyStoreGenerateSessionHost().
Property Documentation
Fingerprint
byte [] SAPTeam.Kryptor.KeyStore.Fingerprint [get]
Gets the unique fingerprint of this keystore.
Definition at line 37 of file KeyStore.cs.
Referenced by SAPTeam.Kryptor.Client.KeyChainCollection.Add(), and SAPTeam.Kryptor.KeyStore.KeyStore().
Keys
byte [][] SAPTeam.Kryptor.KeyStore.Keys [get]
Gets the keys to store.
Definition at line 27 of file KeyStore.cs.
Referenced by SAPTeam.Kryptor.KeyStore.KeyStore(), and SAPTeam.Kryptor.Cli.KeyStoreAnalyze.SessionHost.Start().
Raw
byte [] SAPTeam.Kryptor.KeyStore.Raw [get]
Gets the raw flat bytes array of data.
Definition at line 32 of file KeyStore.cs.
Referenced by SAPTeam.Kryptor.Client.KeyChainCollection.Add(), and SAPTeam.Kryptor.KeyStore.KeyStore().
this[int index]
byte [] SAPTeam.Kryptor.KeyStore.this[int index] [get]
Gets the key at the specified index.
Parameters
index The index of the key to get.
Returns
The key at the specified index.
Definition at line 22 of file KeyStore.cs.
The documentation for this struct was generated from the following file:
KeyStore.cs