SAPTeam.Kryptor.TransformerToken Struct Reference
Parses and holds transformer token data.
Public Member Functions
readonly bool IsValid ()
Determines whether this token is valid.
readonly ITranformer GetTranformer ()
Initializes a new transformer with this token.
readonly KeyStore GenerateKeyStore (int margin)
Generates keystore based on this token data.
Static Public Member Functions
static TransformerToken Parse (string token)
Parses input string to a transformer token.
static bool IsValid (string token)
Determines whether the given token is valid.
Properties
string TransformerName [get, set]
Gets or sets the transformer name.
byte[] SecretKey [get, set]
Gets or sets the secret key.
int KeySize [get, set]
Gets or sets the key size.
byte[] Salt [get, set]
Gets or sets the salt value used for altering seed and outlut data.
int Rotate [get, set]
Gets or sets the number of additional output transformations.
Detailed Description
Parses and holds transformer token data.
Definition at line 10 of file TransformerToken.cs.
Member Function Documentation
GenerateKeyStore()
readonly KeyStore SAPTeam.Kryptor.TransformerToken.GenerateKeyStore (int margin)
Generates keystore based on this token data.
Parameters
margin The requested extra size to make the keystore even more secure.
Returns
A new KeyStore initialized with this token data.
Definition at line 113 of file TransformerToken.cs.
References SAPTeam.Kryptor.ITranformer.Generate(), SAPTeam.Kryptor.TransformerToken.GetTranformer(), SAPTeam.Kryptor.TransformerToken.KeySize, and SAPTeam.Kryptor.TransformerToken.Rotate.
GetTranformer()
readonly ITranformer SAPTeam.Kryptor.TransformerToken.GetTranformer ()
Initializes a new transformer with this token.
Exceptions
ArgumentException
Referenced by SAPTeam.Kryptor.TransformerToken.GenerateKeyStore().
IsValid() [1/2]
readonly bool SAPTeam.Kryptor.TransformerToken.IsValid ()
Determines whether this token is valid.
Returns
IsValid() [2/2]
static bool SAPTeam.Kryptor.TransformerToken.IsValid (string token) [static]
Determines whether the given token is valid.
Parameters
token The token to test.
Returns
Definition at line 85 of file TransformerToken.cs.
Referenced by SAPTeam.Kryptor.Cli.CliSessionHost.CreateKeyStoreLoadSession(), SAPTeam.Kryptor.Cli.Program.GetRootCommand(), SAPTeam.Kryptor.Cli.EncryptionSession.RunAsync(), and SAPTeam.Kryptor.Cli.KeyStoreGenerateSessionHost.Start().
Parse()
static TransformerToken SAPTeam.Kryptor.TransformerToken.Parse (string token) [static]
Parses input string to a transformer token.
Parameters
token The input string with valid transformer token format.
Returns
A new instance of TransformerToken.
Exceptions
ArgumentException
Definition at line 50 of file TransformerToken.cs.
References SAPTeam.Kryptor.TransformerToken.KeySize, SAPTeam.Kryptor.TransformerToken.Rotate, SAPTeam.Kryptor.TransformerToken.Salt, SAPTeam.Kryptor.TransformerToken.SecretKey, and SAPTeam.Kryptor.TransformerToken.TransformerName.
Referenced by SAPTeam.Kryptor.Cli.CliSessionHost.CreateKeyStoreLoadSession().
Property Documentation
KeySize
int SAPTeam.Kryptor.TransformerToken.KeySize [get], [set]
Gets or sets the key size.
Definition at line 28 of file TransformerToken.cs.
Referenced by SAPTeam.Kryptor.TransformerToken.GenerateKeyStore(), and SAPTeam.Kryptor.TransformerToken.Parse().
Rotate
int SAPTeam.Kryptor.TransformerToken.Rotate [get], [set]
Gets or sets the number of additional output transformations.
Definition at line 38 of file TransformerToken.cs.
Referenced by SAPTeam.Kryptor.TransformerToken.GenerateKeyStore(), and SAPTeam.Kryptor.TransformerToken.Parse().
Salt
byte [] SAPTeam.Kryptor.TransformerToken.Salt [get], [set]
Gets or sets the salt value used for altering seed and outlut data.
Definition at line 33 of file TransformerToken.cs.
Referenced by SAPTeam.Kryptor.TransformerToken.Parse().
SecretKey
byte [] SAPTeam.Kryptor.TransformerToken.SecretKey [get], [set]
Gets or sets the secret key.
Definition at line 23 of file TransformerToken.cs.
Referenced by SAPTeam.Kryptor.TransformerToken.Parse().
TransformerName
string SAPTeam.Kryptor.TransformerToken.TransformerName [get], [set]
Gets or sets the transformer name.
Definition at line 18 of file TransformerToken.cs.
Referenced by SAPTeam.Kryptor.TransformerToken.Parse().
The documentation for this struct was generated from the following file:
TransformerToken.cs