SAPTeam.Kryptor.Cli.EncryptionSession Class Reference
Public Member Functions
EncryptionSession (KeyStore keyStore, CryptoProviderConfiguration configuration, int blockSize, int hVerbose, string file, string outputPath)
Public Member Functions inherited from SAPTeam.Kryptor.Client.Session
async Task StartAsync (ISessionHost sessionHost, CancellationToken cancellationToken)
Starts the task asynchronously.
Parameters
sessionHost The parent session host.
cancellationToken A cancellation token to monitor the task.
Returns
A new Task representation of the session.
virtual void ContinueWith (ISession session)
Sets this session as dependency for the given session . The session waits for this session to successfully end.
Parameters
session A session with status SessionStatus.NotStarted.
virtual bool AddDependency (ISession session)
Adds the given session as dependency. this session won't start unless all dependecy session completed successfully. All dependencies must be set before starting the session otherwise it won't have any effects.
Parameters
session The session to be added as dependency.
Returns
true if the session is added to the dependency list and false if the session is not added because this session already started or duplicated session .
virtual bool IsReady (CancellationToken cancellationToken)
Asks from session whether it could be started right now.
Parameters
cancellationToken A cancellation token to monitor the task.
Returns
true if the session has been ready and false when it's not ready.
virtual async Task< TResponse > SendRequest< TResponse > (ISessionHost sessionHost, SessionRequest< TResponse > request, CancellationToken cancellationToken)
Pauses this session and sends the request to the sessionHost to process the request.
Parameters
sessionHost The parent session host.
request The request data.
cancellationToken A cancellation token to monitor the task.
Template Parameters
TResponse The type of requested response from user.
Returns
The response of the end user.
Public Member Functions inherited from SAPTeam.Kryptor.Client.ISession
Protected Member Functions
override async Task< bool > RunAsync (ISessionHost sessionHost, CancellationToken cancellationToken)
Protected Member Functions inherited from SAPTeam.Kryptor.Client.Session
Session ()
Sets all session properties to their default data.
void OnSessionStarted ()
Triggers the SessionStarted event.
void OnProgressChanged ()
Triggers the ProgressChanged event.
void OnDescriptionChanged ()
Triggers the DescriptionChanged event.
void OnPauseStatusChanged ()
Triggers the SessionPaused or SessionResumed events.
void OnStatusChanged ()
Triggers the StatusChanged event.
void OnSessionEnded ()
Triggers the SessionEnded event.
void ThrowIfNotStarted ()
Throws an InvalidOperationException if the session is not started.
void ThrowIfEnded ()
Throws an InvalidOperationException if the session is ended.
Task< bool > RunAsync (ISessionHost sessionHost, CancellationToken cancellationToken)
Starts the session in a managed manner.
Properties
ClientHeader Header [get]
override string Name [get]
Gets the user-friendly name of the session.
Properties inherited from SAPTeam.Kryptor.Client.Session
virtual string Name [get]
Gets the user-friendly name of the session.
virtual double Progress [get, protected set]
Gets the progress percentage of this session.
virtual string Description [get, protected set]
Gets the description of this session.
bool IsRunning [get]
Gets whether this session is running.
bool IsPaused [get, protected set]
Gets whether this session is paused.
virtual bool IsHidden [get]
Gets whether this session is hidden.
SessionStatus Status [get, protected set]
Gets the current status of the session.
SessionEndReason EndReason [get, protected set]
Gets the reason of ending the session.
Exception Exception [get, protected set]
Gets the thrown exception during session run.
Stopwatch Timer [get]
Gets the stopwatch for this session.
List< string > Messages [get]
Gets the message queue of the session. All message will be handled and shown by client application.
List< ISession > Dependencies [get]
Gets the dependency list of the session. This session only starts when all of dependency sessions where completed successfully.
List< ISession > Dependents [get]
Gets the list of the dependents sessions. These sessions only starts when this session where completed successfully. Note this list is only intended for inter session communications and if you want to bind a session with this session you must call either ContinueWith(ISession) or add this session to the target session's Dependencies property.
Properties inherited from SAPTeam.Kryptor.Client.ISession
Additional Inherited Members
Events inherited from SAPTeam.Kryptor.Client.Session
EventHandler< SessionEventArgs > SessionStarted
EventHandler< SessionUpdateEventArgs > ProgressChanged
EventHandler< SessionUpdateEventArgs > DescriptionChanged
EventHandler< SessionEventArgs > StatusChanged
EventHandler< SessionEventArgs > SessionEnded
EventHandler< SessionUpdateEventArgs > SessionPaused
EventHandler< SessionUpdateEventArgs > SessionResumed
Events inherited from SAPTeam.Kryptor.Client.ISession
EventHandler< SessionEventArgs > SessionStarted
Occurs when the session started by SessionManager.
EventHandler< SessionUpdateEventArgs > ProgressChanged
Occurs when the progress value of the session is changed.
EventHandler< SessionUpdateEventArgs > DescriptionChanged
Occurs when the description value is changed.
EventHandler< SessionUpdateEventArgs > SessionPaused
Occurs when the session is paused.
EventHandler< SessionUpdateEventArgs > SessionResumed
Occurs when the session is resumed.
EventHandler< SessionEventArgs > StatusChanged
Occurs when the status of the session is changed.
EventHandler< SessionEventArgs > SessionEnded
Occurs when the session is ended.
Detailed Description
Definition at line 6 of file EncryptionSession.cs.
Constructor & Destructor Documentation
EncryptionSession()
SAPTeam.Kryptor.Cli.EncryptionSession.EncryptionSession (KeyStore keyStore, CryptoProviderConfiguration configuration, int blockSize, int hVerbose, string file, string outputPath)
Definition at line 17 of file EncryptionSession.cs.
References SAPTeam.Kryptor.Client.Session.Description.
Member Function Documentation
RunAsync()
override async Task< bool > SAPTeam.Kryptor.Cli.EncryptionSession.RunAsync (ISessionHost sessionHost, CancellationToken cancellationToken) [protected]
Definition at line 29 of file EncryptionSession.cs.
References SAPTeam.Kryptor.Client.KeyChainCollection.Add(), SAPTeam.Kryptor.Cli.CliHeader.Create(), SAPTeam.Kryptor.Client.Session.Description, SAPTeam.Kryptor.Client.Session.EndReason, SAPTeam.Kryptor.Client.Session.Exception, SAPTeam.Kryptor.Generators.CryptoRandom.Generate(), SAPTeam.Kryptor.Client.ClientHeader.GenerateSerial(), SAPTeam.Kryptor.Generators.CryptoRandom.Instance, SAPTeam.Kryptor.TransformerToken.IsValid(), SAPTeam.Kryptor.Cli.EncryptionSessionHost.KeyChainCollection, SAPTeam.Kryptor.Cli.DataProcessingSessionHost.KeystoreString, SAPTeam.Kryptor.Client.Session.Messages, SAPTeam.Kryptor.Cli.EncryptionSessionHost.Obfuscate, SAPTeam.Kryptor.Cli.EncryptionSessionHost.UseKeyChain, and SAPTeam.Kryptor.Client.SessionHost.Verbose.
Property Documentation
Header
ClientHeader SAPTeam.Kryptor.Cli.EncryptionSession.Header [get]
Definition at line 13 of file EncryptionSession.cs.
Name
override string SAPTeam.Kryptor.Cli.EncryptionSession.Name [get]
Gets the user-friendly name of the session.
Implements SAPTeam.Kryptor.Client.ISession.
Definition at line 15 of file EncryptionSession.cs.
The documentation for this class was generated from the following file:
EncryptionSession.cs