SAPTeam.Kryptor.Client.Security.WordlistIndex Class Reference
Represents schema to store and retrive wordlists informations.
Public Member Functions
void Add (WordlistIndexEntry entry)
Safely Adds new entry to the index.
bool ContainsId (string id)
Determines whether the index contains the specified id.
Properties
WordlistIndexEntry this[string id] [get]
Gets the wordlist by the id.
List< WordlistIndexEntry > Wordlists = new List<WordlistIndexEntry>() [get, set]
Gets or sets the wordlists container.
Detailed Description
Represents schema to store and retrive wordlists informations.
Definition at line 6 of file WordlistIndex.cs.
Member Function Documentation
Add()
void SAPTeam.Kryptor.Client.Security.WordlistIndex.Add (WordlistIndexEntry entry)
Safely Adds new entry to the index.
Parameters
entry The wordlist entry.
Exceptions
ArgumentException
Definition at line 42 of file WordlistIndex.cs.
References SAPTeam.Kryptor.Client.Security.WordlistIndex.ContainsId(), SAPTeam.Kryptor.Client.Security.WordlistIndexEntry.Hash, SAPTeam.Kryptor.Client.Security.WordlistIndexEntry.Id, and SAPTeam.Kryptor.Client.Security.WordlistIndex.Wordlists.
Referenced by SAPTeam.Kryptor.Cli.Wordlist.SessionHost.FinalizeInstallation().
ContainsId()
bool SAPTeam.Kryptor.Client.Security.WordlistIndex.ContainsId (string id)
Determines whether the index contains the specified id.
Parameters
id The id to search.
Returns
Referenced by SAPTeam.Kryptor.Client.Security.WordlistIndex.Add(), and SAPTeam.Kryptor.Cli.Wordlist.SessionHost.GetInstallationPermission().
Property Documentation
this[string id]
WordlistIndexEntry SAPTeam.Kryptor.Client.Security.WordlistIndex.this[string id] [get]
Gets the wordlist by the id.
Parameters
id The id of the wordlist.
Returns
Definition at line 15 of file WordlistIndex.cs.
Wordlists
List<WordlistIndexEntry> SAPTeam.Kryptor.Client.Security.WordlistIndex.Wordlists = new List<WordlistIndexEntry>() [get], [set]
Gets or sets the wordlists container.
Definition at line 33 of file WordlistIndex.cs.
Referenced by SAPTeam.Kryptor.Client.Security.WordlistIndex.Add(), SAPTeam.Kryptor.Cli.Wordlist.SessionHost.ListInstalledWordlists(), SAPTeam.Kryptor.Cli.Wordlist.SessionHost.RemoveWordlist(), SAPTeam.Kryptor.Cli.Wordlist.SessionHost.SortIndex(), SAPTeam.Kryptor.Cli.Wordlist.IndexSessionHost.Start(), and SAPTeam.Kryptor.Cli.Wordlist.InstallSessionHost.Start().
The documentation for this class was generated from the following file:
WordlistIndex.cs