name: Gawe CI for Kryptor CLI

on:
  workflow_dispatch:
    inputs:
      deploy:
        description: Create and Deploy package
        type: boolean
        default: true
      nuget-deploy:
        description: Deploy package to NuGet gallery
        type: boolean
        default: true
  push:
    paths:
      - 'src/Kryptor.Client/**'
      - 'cli/**'
    branches: [master, dev]
  pull_request:
    branches: [master]
    
permissions:
  checks: 
    write
  contents:
    write
  packages:
    write
  pull-requests:
    write

jobs:
  build:
    uses: SAPTeamDEV/Gawe/.github/workflows/dotnet.yml@master
    with:
      build-path: 'src/Kryptor.Client/Kryptor.Client.csproj cli/*/*.csproj'
      test-path: ''
      deploy-path: 'src/Kryptor.Client/Kryptor.Client.csproj cli/*/*.csproj'
      deploy: ${{ !contains(inputs.deploy, 'false') }}
      nuget-deploy: ${{ !contains(inputs.nuget-deploy, 'false') }}
    secrets: inherit
  
  publish-debug:
    name: Publish Debug Artifacts
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: | 
            6.0.x
            8.0.x
      - name: Build debug binaries
        run: |
          tools/publish.sh -d
        shell: bash
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ github.sha }}
          path: |
            bin/Publish/Cli/Debug
          compression-level: 9