name: Gawe CI for Kryptor Core Libraries

on:
  workflow_dispatch:
    inputs:
      deploy:
        description: Create and Deploy package
        type: boolean
        default: true
      nuget-deploy:
        description: Deploy package to NuGet gallery
        type: boolean
        default: true
  push:
    paths:
      - 'src/Kryptor/**'
      - 'test/Kryptor.Tests/**'
    branches: [master, dev]
  pull_request:
    branches: [master]
    
permissions:
  checks: 
    write
  contents:
    write
  packages:
    write
  pull-requests:
    write

jobs:
  build:
    uses: SAPTeamDEV/Gawe/.github/workflows/dotnet.yml@master
    with:
      build-path: 'src/Kryptor/Kryptor.csproj'
      test-path: 'test/Kryptor.Tests/Kryptor.Tests.csproj'
      deploy-path: 'src/Kryptor/Kryptor.csproj'
      deploy: ${{ !contains(inputs.deploy, 'false') }}
      nuget-deploy: ${{ !contains(inputs.nuget-deploy, 'false') }}
    secrets: inherit
