name: Wordlist Index Updater

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  publish:
    name: Publish index
    runs-on: ubuntu-latest
    
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: | 
            6.0.x
            8.0.x
      - name: Install dependencies
        run: |
          dotnet restore
      - name: Build
        run: |
            dotnet build cli/Kryptor.Cli/Kryptor.Cli.csproj -f net6.0 --configuration Debug --no-restore -o bin
        shell: bash
      - name: Update Index
        run: |
          bin/Kryptor w c Wordlist-Index.json Wordlist-IndexV2.json
        shell: bash
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update wordlist index
      